# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'querschnitt.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_q_dock(object):
    def setupUi(self, q_dock):
        q_dock.setObjectName("q_dock")
        q_dock.resize(1354, 664)
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.dockWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox_5 = QtWidgets.QGroupBox(self.dockWidgetContents)
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.qp_widget = QtWidgets.QTabWidget(self.groupBox_5)
        self.qp_widget.setEnabled(True)
        self.qp_widget.setMaximumSize(QtCore.QSize(400, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.qp_widget.setFont(font)
        self.qp_widget.setObjectName("qp_widget")
        self.pro_prop = QtWidgets.QWidget()
        self.pro_prop.setObjectName("pro_prop")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.pro_prop)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_88 = QtWidgets.QLabel(self.pro_prop)
        self.label_88.setObjectName("label_88")
        self.gridLayout_9.addWidget(self.label_88, 1, 1, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.pro_prop)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setUnderline(False)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_9.addWidget(self.label_4, 3, 1, 1, 2)
        self.edit_knoten = QtWidgets.QLineEdit(self.pro_prop)
        self.edit_knoten.setEnabled(False)
        self.edit_knoten.setObjectName("edit_knoten")
        self.gridLayout_9.addWidget(self.edit_knoten, 0, 3, 1, 2)
        self.pro_rw = QtWidgets.QLineEdit(self.pro_prop)
        self.pro_rw.setEnabled(False)
        self.pro_rw.setObjectName("pro_rw")
        self.gridLayout_9.addWidget(self.pro_rw, 6, 3, 1, 1)
        self.modus_label = QtWidgets.QComboBox(self.pro_prop)
        self.modus_label.setEnabled(False)
        self.modus_label.setObjectName("modus_label")
        self.modus_label.addItem("")
        self.modus_label.addItem("")
        self.modus_label.addItem("")
        self.modus_label.addItem("")
        self.modus_label.addItem("")
        self.modus_label.addItem("")
        self.modus_label.addItem("")
        self.modus_label.addItem("")
        self.modus_label.addItem("")
        self.gridLayout_9.addWidget(self.modus_label, 4, 3, 1, 2)
        self.label_5 = QtWidgets.QLabel(self.pro_prop)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setUnderline(False)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_9.addWidget(self.label_5, 4, 1, 1, 2)
        self.ddddd = QtWidgets.QLabel(self.pro_prop)
        self.ddddd.setObjectName("ddddd")
        self.gridLayout_9.addWidget(self.ddddd, 6, 1, 1, 1)
        self.plot_editor_box = QtWidgets.QGroupBox(self.pro_prop)
        self.plot_editor_box.setObjectName("plot_editor_box")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.plot_editor_box)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.coords_table = QtWidgets.QTableWidget(self.plot_editor_box)
        self.coords_table.setMinimumSize(QtCore.QSize(140, 0))
        self.coords_table.setToolTipDuration(-8)
        self.coords_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.coords_table.setProperty("showDropIndicator", False)
        self.coords_table.setDragDropOverwriteMode(False)
        self.coords_table.setAlternatingRowColors(True)
        self.coords_table.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.coords_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.coords_table.setColumnCount(2)
        self.coords_table.setObjectName("coords_table")
        self.coords_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.coords_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.coords_table.setHorizontalHeaderItem(1, item)
        self.gridLayout_7.addWidget(self.coords_table, 4, 0, 1, 4)
        self.groupBox = QtWidgets.QGroupBox(self.plot_editor_box)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self._rschalter = QtWidgets.QRadioButton(self.groupBox)
        self._rschalter.setEnabled(False)
        self._rschalter.setObjectName("_rschalter")
        self.gridLayout_3.addWidget(self._rschalter, 0, 2, 1, 1)
        self._rquer = QtWidgets.QRadioButton(self.groupBox)
        self._rquer.setEnabled(True)
        self._rquer.setChecked(True)
        self._rquer.setObjectName("_rquer")
        self.gridLayout_3.addWidget(self._rquer, 0, 0, 1, 1)
        self._rrau = QtWidgets.QRadioButton(self.groupBox)
        self._rrau.setEnabled(False)
        self._rrau.setObjectName("_rrau")
        self.gridLayout_3.addWidget(self._rrau, 0, 1, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox, 1, 0, 1, 3)
        self.groupBox_2 = QtWidgets.QGroupBox(self.plot_editor_box)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.redo = QtWidgets.QPushButton(self.groupBox_2)
        self.redo.setEnabled(False)
        self.redo.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../icons/redo3.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.redo.setIcon(icon)
        self.redo.setObjectName("redo")
        self.gridLayout_19.addWidget(self.redo, 0, 1, 1, 1)
        self.undo = QtWidgets.QPushButton(self.groupBox_2)
        self.undo.setEnabled(False)
        self.undo.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../icons/undo3.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.undo.setIcon(icon1)
        self.undo.setObjectName("undo")
        self.gridLayout_19.addWidget(self.undo, 0, 0, 1, 1)
        self.copy_clip = QtWidgets.QPushButton(self.groupBox_2)
        self.copy_clip.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../icons/copy.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.copy_clip.setIcon(icon2)
        self.copy_clip.setObjectName("copy_clip")
        self.gridLayout_19.addWidget(self.copy_clip, 0, 3, 1, 1)
        self.paste_clip = QtWidgets.QPushButton(self.groupBox_2)
        self.paste_clip.setEnabled(False)
        self.paste_clip.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../icons/Paste.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.paste_clip.setIcon(icon3)
        self.paste_clip.setObjectName("paste_clip")
        self.gridLayout_19.addWidget(self.paste_clip, 0, 4, 1, 1)
        self.delete_rows = QtWidgets.QPushButton(self.groupBox_2)
        self.delete_rows.setEnabled(False)
        self.delete_rows.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../icons/delete.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.delete_rows.setIcon(icon4)
        self.delete_rows.setObjectName("delete_rows")
        self.gridLayout_19.addWidget(self.delete_rows, 0, 2, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_2, 1, 3, 1, 1)
        self.gridLayout_7.setColumnStretch(0, 1)
        self.gridLayout_9.addWidget(self.plot_editor_box, 8, 1, 1, 4)
        self.edit_pname = QtWidgets.QLineEdit(self.pro_prop)
        self.edit_pname.setEnabled(False)
        self.edit_pname.setObjectName("edit_pname")
        self.gridLayout_9.addWidget(self.edit_pname, 2, 3, 1, 2)
        self.label_6 = QtWidgets.QLabel(self.pro_prop)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setUnderline(False)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_9.addWidget(self.label_6, 5, 1, 1, 2)
        self.label_73 = QtWidgets.QLabel(self.pro_prop)
        self.label_73.setObjectName("label_73")
        self.gridLayout_9.addWidget(self.label_73, 0, 1, 1, 2)
        self.label_90 = QtWidgets.QLabel(self.pro_prop)
        self.label_90.setObjectName("label_90")
        self.gridLayout_9.addWidget(self.label_90, 2, 1, 1, 2)
        self.ctab_label = QtWidgets.QComboBox(self.pro_prop)
        self.ctab_label.setEnabled(False)
        self.ctab_label.setObjectName("ctab_label")
        self.ctab_label.addItem("")
        self.ctab_label.addItem("")
        self.gridLayout_9.addWidget(self.ctab_label, 3, 3, 1, 2)
        self.maxHeight_label = QtWidgets.QLineEdit(self.pro_prop)
        self.maxHeight_label.setEnabled(False)
        self.maxHeight_label.setObjectName("maxHeight_label")
        self.gridLayout_9.addWidget(self.maxHeight_label, 5, 3, 1, 2)
        self.edit_station = QtWidgets.QLineEdit(self.pro_prop)
        self.edit_station.setEnabled(False)
        self.edit_station.setObjectName("edit_station")
        self.gridLayout_9.addWidget(self.edit_station, 1, 3, 1, 2)
        self.label_82 = QtWidgets.QLabel(self.pro_prop)
        self.label_82.setObjectName("label_82")
        self.gridLayout_9.addWidget(self.label_82, 7, 1, 1, 1)
        self.pro_hw = QtWidgets.QLineEdit(self.pro_prop)
        self.pro_hw.setEnabled(False)
        self.pro_hw.setObjectName("pro_hw")
        self.gridLayout_9.addWidget(self.pro_hw, 7, 3, 1, 1)
        self.qp_widget.addTab(self.pro_prop, "")
        self.geo_info_2 = QtWidgets.QWidget()
        self.geo_info_2.setObjectName("geo_info_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.geo_info_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.geo_info = QtWidgets.QGroupBox(self.geo_info_2)
        self.geo_info.setEnabled(False)
        self.geo_info.setTitle("")
        self.geo_info.setObjectName("geo_info")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.geo_info)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.gi_width = QtWidgets.QLineEdit(self.geo_info)
        self.gi_width.setObjectName("gi_width")
        self.gridLayout_15.addWidget(self.gi_width, 2, 1, 1, 1)
        self.label_68 = QtWidgets.QLabel(self.geo_info)
        self.label_68.setObjectName("label_68")
        self.gridLayout_15.addWidget(self.label_68, 0, 0, 1, 1)
        self.label_69 = QtWidgets.QLabel(self.geo_info)
        self.label_69.setObjectName("label_69")
        self.gridLayout_15.addWidget(self.label_69, 2, 0, 1, 1)
        self.gi_xl = QtWidgets.QLineEdit(self.geo_info)
        self.gi_xl.setObjectName("gi_xl")
        self.gridLayout_15.addWidget(self.gi_xl, 6, 1, 1, 1)
        self.gi_kstime = QtWidgets.QLineEdit(self.geo_info)
        self.gi_kstime.setObjectName("gi_kstime")
        self.gridLayout_15.addWidget(self.gi_kstime, 5, 1, 1, 1)
        self.gi_id = QtWidgets.QLineEdit(self.geo_info)
        self.gi_id.setObjectName("gi_id")
        self.gridLayout_15.addWidget(self.gi_id, 1, 1, 1, 1)
        self.label_87 = QtWidgets.QLabel(self.geo_info)
        self.label_87.setObjectName("label_87")
        self.gridLayout_15.addWidget(self.label_87, 5, 0, 1, 1)
        self.gi_heit = QtWidgets.QLineEdit(self.geo_info)
        self.gi_heit.setObjectName("gi_heit")
        self.gridLayout_15.addWidget(self.gi_heit, 3, 1, 1, 1)
        self.label_89 = QtWidgets.QLabel(self.geo_info)
        self.label_89.setObjectName("label_89")
        self.gridLayout_15.addWidget(self.label_89, 6, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.geo_info)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_15.addWidget(self.label_8, 7, 0, 1, 2)
        self.gi_ityp = QtWidgets.QComboBox(self.geo_info)
        self.gi_ityp.setEditable(False)
        self.gi_ityp.setObjectName("gi_ityp")
        self.gi_ityp.addItem("")
        self.gi_ityp.addItem("")
        self.gi_ityp.addItem("")
        self.gi_ityp.addItem("")
        self.gi_ityp.addItem("")
        self.gi_ityp.addItem("")
        self.gi_ityp.addItem("")
        self.gi_ityp.addItem("")
        self.gi_ityp.addItem("")
        self.gridLayout_15.addWidget(self.gi_ityp, 0, 1, 1, 1)
        self.label_70 = QtWidgets.QLabel(self.geo_info)
        self.label_70.setObjectName("label_70")
        self.gridLayout_15.addWidget(self.label_70, 3, 0, 1, 1)
        self.gi_zo = QtWidgets.QLineEdit(self.geo_info)
        self.gi_zo.setObjectName("gi_zo")
        self.gridLayout_15.addWidget(self.gi_zo, 4, 1, 1, 1)
        self.label_74 = QtWidgets.QLabel(self.geo_info)
        self.label_74.setObjectName("label_74")
        self.gridLayout_15.addWidget(self.label_74, 4, 0, 1, 1)
        self.label_80 = QtWidgets.QLabel(self.geo_info)
        self.label_80.setObjectName("label_80")
        self.gridLayout_15.addWidget(self.label_80, 1, 0, 1, 1)
        self.label_71 = QtWidgets.QLabel(self.geo_info)
        self.label_71.setObjectName("label_71")
        self.gridLayout_15.addWidget(self.label_71, 8, 0, 1, 1)
        self.gi_ztr = QtWidgets.QLineEdit(self.geo_info)
        self.gi_ztr.setObjectName("gi_ztr")
        self.gridLayout_15.addWidget(self.gi_ztr, 8, 1, 1, 1)
        self.label_72 = QtWidgets.QLabel(self.geo_info)
        self.label_72.setObjectName("label_72")
        self.gridLayout_15.addWidget(self.label_72, 9, 0, 1, 1)
        self.gi_ztl = QtWidgets.QLineEdit(self.geo_info)
        self.gi_ztl.setObjectName("gi_ztl")
        self.gridLayout_15.addWidget(self.gi_ztl, 9, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.geo_info)
        self.ovf_modbox = QtWidgets.QGroupBox(self.geo_info_2)
        self.ovf_modbox.setEnabled(False)
        self.ovf_modbox.setObjectName("ovf_modbox")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.ovf_modbox)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label_9 = QtWidgets.QLabel(self.ovf_modbox)
        self.label_9.setObjectName("label_9")
        self.gridLayout_12.addWidget(self.label_9, 4, 2, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.ovf_modbox)
        self.label_17.setObjectName("label_17")
        self.gridLayout_12.addWidget(self.label_17, 3, 0, 1, 1)
        self.gi_novf = QtWidgets.QLineEdit(self.ovf_modbox)
        self.gi_novf.setObjectName("gi_novf")
        self.gridLayout_12.addWidget(self.gi_novf, 1, 1, 1, 1)
        self.gi_ovfaus = QtWidgets.QLineEdit(self.ovf_modbox)
        self.gi_ovfaus.setObjectName("gi_ovfaus")
        self.gridLayout_12.addWidget(self.gi_ovfaus, 3, 3, 1, 1)
        self.gi_tovfan = QtWidgets.QLineEdit(self.ovf_modbox)
        self.gi_tovfan.setObjectName("gi_tovfan")
        self.gridLayout_12.addWidget(self.gi_tovfan, 5, 1, 1, 1)
        self.label_86 = QtWidgets.QLabel(self.ovf_modbox)
        self.label_86.setObjectName("label_86")
        self.gridLayout_12.addWidget(self.label_86, 5, 2, 1, 1)
        self.gi_iabovf = QtWidgets.QLineEdit(self.ovf_modbox)
        self.gi_iabovf.setObjectName("gi_iabovf")
        self.gridLayout_12.addWidget(self.gi_iabovf, 1, 3, 1, 1)
        self.label_85 = QtWidgets.QLabel(self.ovf_modbox)
        self.label_85.setObjectName("label_85")
        self.gridLayout_12.addWidget(self.label_85, 5, 0, 1, 1)
        self.label_64 = QtWidgets.QLabel(self.ovf_modbox)
        self.label_64.setObjectName("label_64")
        self.gridLayout_12.addWidget(self.label_64, 3, 2, 1, 1)
        self.gi_lire = QtWidgets.QComboBox(self.ovf_modbox)
        self.gi_lire.setObjectName("gi_lire")
        self.gi_lire.addItem("")
        self.gi_lire.addItem("")
        self.gi_lire.addItem("")
        self.gridLayout_12.addWidget(self.gi_lire, 0, 2, 1, 2)
        self.label_14 = QtWidgets.QLabel(self.ovf_modbox)
        self.label_14.setObjectName("label_14")
        self.gridLayout_12.addWidget(self.label_14, 1, 2, 1, 1)
        self.gi_qomax = QtWidgets.QLineEdit(self.ovf_modbox)
        self.gi_qomax.setObjectName("gi_qomax")
        self.gridLayout_12.addWidget(self.gi_qomax, 4, 1, 1, 1)
        self.label_81 = QtWidgets.QLabel(self.ovf_modbox)
        self.label_81.setObjectName("label_81")
        self.gridLayout_12.addWidget(self.label_81, 4, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.ovf_modbox)
        self.label_13.setObjectName("label_13")
        self.gridLayout_12.addWidget(self.label_13, 1, 0, 1, 1)
        self.gi_ovfan = QtWidgets.QLineEdit(self.ovf_modbox)
        self.gi_ovfan.setObjectName("gi_ovfan")
        self.gridLayout_12.addWidget(self.gi_ovfan, 3, 1, 1, 1)
        self.gi_qregel = QtWidgets.QLineEdit(self.ovf_modbox)
        self.gi_qregel.setObjectName("gi_qregel")
        self.gridLayout_12.addWidget(self.gi_qregel, 4, 3, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.ovf_modbox)
        self.label_12.setObjectName("label_12")
        self.gridLayout_12.addWidget(self.label_12, 0, 0, 1, 2)
        self.gi_tovfaus = QtWidgets.QLineEdit(self.ovf_modbox)
        self.gi_tovfaus.setObjectName("gi_tovfaus")
        self.gridLayout_12.addWidget(self.gi_tovfaus, 5, 3, 1, 1)
        self.verticalLayout_2.addWidget(self.ovf_modbox)
        self.qp_widget.addTab(self.geo_info_2, "")
        self.wsp_rau_box2 = QtWidgets.QWidget()
        self.wsp_rau_box2.setObjectName("wsp_rau_box2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.wsp_rau_box2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.wsp_rau_box = QtWidgets.QGroupBox(self.wsp_rau_box2)
        self.wsp_rau_box.setEnabled(False)
        self.wsp_rau_box.setTitle("")
        self.wsp_rau_box.setObjectName("wsp_rau_box")
        self.gridLayout = QtWidgets.QGridLayout(self.wsp_rau_box)
        self.gridLayout.setObjectName("gridLayout")
        self.label_75 = QtWidgets.QLabel(self.wsp_rau_box)
        self.label_75.setObjectName("label_75")
        self.gridLayout.addWidget(self.label_75, 0, 0, 1, 1)
        self.gi_dzero = QtWidgets.QLineEdit(self.wsp_rau_box)
        self.gi_dzero.setObjectName("gi_dzero")
        self.gridLayout.addWidget(self.gi_dzero, 1, 1, 1, 1)
        self.label_77 = QtWidgets.QLabel(self.wsp_rau_box)
        self.label_77.setObjectName("label_77")
        self.gridLayout.addWidget(self.label_77, 2, 0, 1, 1)
        self.label_83 = QtWidgets.QLabel(self.wsp_rau_box)
        self.label_83.setObjectName("label_83")
        self.gridLayout.addWidget(self.label_83, 6, 0, 1, 1)
        self.gi_zs = QtWidgets.QLineEdit(self.wsp_rau_box)
        self.gi_zs.setObjectName("gi_zs")
        self.gridLayout.addWidget(self.gi_zs, 3, 1, 1, 1)
        self.label_84 = QtWidgets.QLabel(self.wsp_rau_box)
        self.label_84.setObjectName("label_84")
        self.gridLayout.addWidget(self.label_84, 4, 0, 1, 1)
        self.gi_sf = QtWidgets.QLineEdit(self.wsp_rau_box)
        self.gi_sf.setObjectName("gi_sf")
        self.gridLayout.addWidget(self.gi_sf, 6, 1, 1, 1)
        self.wsp_ckm = QtWidgets.QLineEdit(self.wsp_rau_box)
        self.wsp_ckm.setObjectName("wsp_ckm")
        self.gridLayout.addWidget(self.wsp_ckm, 5, 1, 1, 1)
        self.gi_qzero = QtWidgets.QLineEdit(self.wsp_rau_box)
        self.gi_qzero.setObjectName("gi_qzero")
        self.gridLayout.addWidget(self.gi_qzero, 2, 1, 1, 1)
        self.wsp_hr0 = QtWidgets.QLineEdit(self.wsp_rau_box)
        self.wsp_hr0.setObjectName("wsp_hr0")
        self.gridLayout.addWidget(self.wsp_hr0, 4, 1, 1, 1)
        self.gi_rni = QtWidgets.QLineEdit(self.wsp_rau_box)
        self.gi_rni.setObjectName("gi_rni")
        self.gridLayout.addWidget(self.gi_rni, 0, 1, 1, 1)
        self.label_76 = QtWidgets.QLabel(self.wsp_rau_box)
        self.label_76.setObjectName("label_76")
        self.gridLayout.addWidget(self.label_76, 1, 0, 1, 1)
        self.label_78 = QtWidgets.QLabel(self.wsp_rau_box)
        self.label_78.setObjectName("label_78")
        self.gridLayout.addWidget(self.label_78, 3, 0, 1, 1)
        self.label_79 = QtWidgets.QLabel(self.wsp_rau_box)
        self.label_79.setObjectName("label_79")
        self.gridLayout.addWidget(self.label_79, 5, 0, 1, 1)
        self.wsp_table = QtWidgets.QTableWidget(self.wsp_rau_box)
        self.wsp_table.setObjectName("wsp_table")
        self.wsp_table.setColumnCount(2)
        self.wsp_table.setRowCount(7)
        item = QtWidgets.QTableWidgetItem()
        self.wsp_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.wsp_table.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.wsp_table.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.wsp_table.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.wsp_table.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.wsp_table.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.wsp_table.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.wsp_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.wsp_table.setHorizontalHeaderItem(1, item)
        self.gridLayout.addWidget(self.wsp_table, 7, 0, 1, 2)
        self.verticalLayout_3.addWidget(self.wsp_rau_box)
        self.qp_widget.addTab(self.wsp_rau_box2, "")
        self.gridLayout_21.addWidget(self.qp_widget, 0, 1, 3, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_4.setMaximumSize(QtCore.QSize(16777215, 50))
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox_4)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.knotenNr = QtWidgets.QComboBox(self.groupBox_4)
        self.knotenNr.setMinimumSize(QtCore.QSize(80, 0))
        self.knotenNr.setMaximumSize(QtCore.QSize(80, 16777215))
        self.knotenNr.setEditable(False)
        self.knotenNr.setMaxVisibleItems(100)
        self.knotenNr.setObjectName("knotenNr")
        self.horizontalLayout.addWidget(self.knotenNr)
        self.label_15 = QtWidgets.QLabel(self.groupBox_4)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout.addWidget(self.label_15)
        self.station_label = QtWidgets.QComboBox(self.groupBox_4)
        self.station_label.setMinimumSize(QtCore.QSize(120, 0))
        self.station_label.setMaximumSize(QtCore.QSize(150, 16777215))
        self.station_label.setEditable(False)
        self.station_label.setMaxVisibleItems(100)
        self.station_label.setObjectName("station_label")
        self.horizontalLayout.addWidget(self.station_label)
        self.label_7 = QtWidgets.QLabel(self.groupBox_4)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.label_7)
        self.schnittName_label = QtWidgets.QComboBox(self.groupBox_4)
        self.schnittName_label.setMinimumSize(QtCore.QSize(200, 0))
        self.schnittName_label.setMaximumSize(QtCore.QSize(220, 16777215))
        self.schnittName_label.setEditable(False)
        self.schnittName_label.setMaxVisibleItems(100)
        self.schnittName_label.setObjectName("schnittName_label")
        self.horizontalLayout.addWidget(self.schnittName_label)
        self.label_3 = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setUnderline(False)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.Punkte_label = QtWidgets.QLCDNumber(self.groupBox_4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Punkte_label.setFont(font)
        self.Punkte_label.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.Punkte_label.setObjectName("Punkte_label")
        self.horizontalLayout.addWidget(self.Punkte_label)
        self.label_2 = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setUnderline(False)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.AspectRatio = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.AspectRatio.setDecimals(3)
        self.AspectRatio.setMinimum(0.1)
        self.AspectRatio.setProperty("value", 1.0)
        self.AspectRatio.setObjectName("AspectRatio")
        self.horizontalLayout.addWidget(self.AspectRatio)
        self.gridLayout_21.addWidget(self.groupBox_4, 0, 0, 1, 1)
        self.splitter = QtWidgets.QSplitter(self.groupBox_5)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.graphicsView = PlotWidget(self.splitter)
        self.graphicsView.setLineWidth(2)
        self.graphicsView.setObjectName("graphicsView")
        self.graphicsView2 = PlotWidget(self.splitter)
        self.graphicsView2.setLineWidth(2)
        brush = QtGui.QBrush(QtGui.QColor(222, 222, 222))
        brush.setStyle(QtCore.Qt.SolidPattern)
        self.graphicsView2.setBackgroundBrush(brush)
        self.graphicsView2.setObjectName("graphicsView2")
        self.gridLayout_21.addWidget(self.splitter, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_5, 0, 0, 1, 1)
        q_dock.setWidget(self.dockWidgetContents)

        self.retranslateUi(q_dock)
        self.qp_widget.setCurrentIndex(0)
        self.ctab_label.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(q_dock)

    def retranslateUi(self, q_dock):
        _translate = QtCore.QCoreApplication.translate
        q_dock.setWindowTitle(_translate("q_dock", "Querschnitt"))
        self.label_88.setText(_translate("q_dock", "Station [m]"))
        self.label_4.setText(_translate("q_dock", "Profilauswertung:"))
        self.modus_label.setToolTip(_translate("q_dock", "<html><head/><body><p><span style=\" font-weight:600;\">Querprofil:</span></p><p>V = wie eingegeben</p><p>R = Reduziert zwischen linkem und rechtem Hochpunkt </p><p><span style=\" font-weight:600;\">Breitflächiger Abfluss (bQ):</span></p><p>K = Kernquerschnitt, bQ erst wenn WSP&gt;K</p><p>F = vollen Querschnitt, bQ von Anfang an</p><p><br/></p><p>DF = Abfluss nur innerhalb des Bauwerks (Für die Ermittlung der Leistungsfähigkeit eines Bauwerks)</p><p>OF = (<span style=\" font-weight:600;\">O</span>verland<span style=\" font-weight:600;\">F</span>low) Bauwerk wird als komplett verklaust angenommen, Der gesamte Abfluss fließt über das Gelände ab</p><p>H2 = Rauhigkeitsprofil mit negativer Knotennummer</p><p>ZS = Schaltprofil</p></body></html>"))
        self.modus_label.setItemText(0, _translate("q_dock", "VK"))
        self.modus_label.setItemText(1, _translate("q_dock", "RK"))
        self.modus_label.setItemText(2, _translate("q_dock", "VF"))
        self.modus_label.setItemText(3, _translate("q_dock", "RF"))
        self.modus_label.setItemText(4, _translate("q_dock", "DF"))
        self.modus_label.setItemText(5, _translate("q_dock", "OF"))
        self.modus_label.setItemText(6, _translate("q_dock", "H2"))
        self.modus_label.setItemText(7, _translate("q_dock", "RS"))
        self.modus_label.setItemText(8, _translate("q_dock", "ZS"))
        self.label_5.setText(_translate("q_dock", "Querschnittsparameter:"))
        self.ddddd.setText(_translate("q_dock", "X:"))
        self.plot_editor_box.setTitle(_translate("q_dock", "Profil"))
        item = self.coords_table.horizontalHeaderItem(0)
        item.setText(_translate("q_dock", "X"))
        item = self.coords_table.horizontalHeaderItem(1)
        item.setText(_translate("q_dock", "Y"))
        self._rschalter.setText(_translate("q_dock", "Schalt"))
        self._rquer.setText(_translate("q_dock", "Quer"))
        self._rrau.setText(_translate("q_dock", "Rau"))
        self.redo.setToolTip(_translate("q_dock", "redo"))
        self.redo.setShortcut(_translate("q_dock", "Ctrl+Y"))
        self.undo.setToolTip(_translate("q_dock", "undo"))
        self.undo.setShortcut(_translate("q_dock", "Ctrl+Z"))
        self.copy_clip.setToolTip(_translate("q_dock", "Copy"))
        self.copy_clip.setShortcut(_translate("q_dock", "Ctrl+C"))
        self.paste_clip.setToolTip(_translate("q_dock", "Paste"))
        self.paste_clip.setShortcut(_translate("q_dock", "Ctrl+V"))
        self.delete_rows.setToolTip(_translate("q_dock", "Delete rows"))
        self.delete_rows.setShortcut(_translate("q_dock", "Del"))
        self.label_6.setText(_translate("q_dock", "<html><head/><body><p>Maximale Höhe:</p></body></html>"))
        self.label_73.setText(_translate("q_dock", "Knoten Nummer"))
        self.label_90.setText(_translate("q_dock", "Profil Name"))
        self.ctab_label.setToolTip(_translate("q_dock", "\"CTAB\", Wenn \"ON\", werden Details der Profilauswetung in *.OUT geschrieben"))
        self.ctab_label.setItemText(0, _translate("q_dock", "OFF"))
        self.ctab_label.setItemText(1, _translate("q_dock", "ON"))
        self.label_82.setText(_translate("q_dock", "<html><head/><body><p>Y:</p></body></html>"))
        self.qp_widget.setTabText(self.qp_widget.indexOf(self.pro_prop), _translate("q_dock", "Profil Info"))
        self.gi_width.setToolTip(_translate("q_dock", "<html><head/><body><p>Kreis: Durchmesser</p><p>Rechteck, Trapez: Sohlbreite</p></body></html>"))
        self.label_68.setText(_translate("q_dock", "Profil Typ:"))
        self.label_69.setText(_translate("q_dock", "Querschnittsbreite [m]"))
        self.gi_xl.setToolTip(_translate("q_dock", "<html><head/><body><p>Entfernung bis zum nächsten stromabwärts liegenden Verb. knoten</p></body></html>"))
        self.label_87.setText(_translate("q_dock", "Verkrautung"))
        self.label_89.setText(_translate("q_dock", "Entfernung"))
        self.label_8.setText(_translate("q_dock", "Neigung der Böschung (beim Profil Typ: Trapez)"))
        self.gi_ityp.setItemText(0, _translate("q_dock", "Kreisquerschnitt (1)"))
        self.gi_ityp.setItemText(1, _translate("q_dock", "Rechteckquerschnitt (2)"))
        self.gi_ityp.setItemText(2, _translate("q_dock", "Trapezquerschnitt (3)"))
        self.gi_ityp.setItemText(3, _translate("q_dock", "beliebiger Querschnitt (4)"))
        self.gi_ityp.setItemText(4, _translate("q_dock", "(INTERN) interpoliertes querschnitt (5)"))
        self.gi_ityp.setItemText(5, _translate("q_dock", "interpoliertes Zusatzquerprofil (6)"))
        self.gi_ityp.setItemText(6, _translate("q_dock", "(7)"))
        self.gi_ityp.setItemText(7, _translate("q_dock", "interpoliertes Bauwersprofil (8)"))
        self.gi_ityp.setItemText(8, _translate("q_dock", "Bauwerksprofil (9)"))
        self.label_70.setText(_translate("q_dock", "Querschnittshöhe [m]"))
        self.label_74.setText(_translate("q_dock", "Sohlhöhe [m+NN]"))
        self.label_80.setText(_translate("q_dock", "Gewässer ID"))
        self.label_71.setText(_translate("q_dock", "Rechts                            "))
        self.label_72.setText(_translate("q_dock", "Links"))
        self.ovf_modbox.setTitle(_translate("q_dock", "Overflow Mode"))
        self.label_9.setText(_translate("q_dock", "Q Regel"))
        self.label_17.setText(_translate("q_dock", "An"))
        self.label_86.setText(_translate("q_dock", "T Aus"))
        self.label_85.setText(_translate("q_dock", "T An"))
        self.label_64.setText(_translate("q_dock", "Aus"))
        self.gi_lire.setItemText(0, _translate("q_dock", "Gleich"))
        self.gi_lire.setItemText(1, _translate("q_dock", "Links"))
        self.gi_lire.setItemText(2, _translate("q_dock", "Rechts"))
        self.label_14.setText(_translate("q_dock", "Knoten"))
        self.label_81.setText(_translate("q_dock", "Q Max"))
        self.label_13.setText(_translate("q_dock", "Anzahl"))
        self.label_12.setText(_translate("q_dock", "Niedriger BOK"))
        self.qp_widget.setTabText(self.qp_widget.indexOf(self.geo_info_2), _translate("q_dock", "Geometrie Info"))
        self.label_75.setText(_translate("q_dock", "<html><head/><body><p>Rauhigkeit</p></body></html>"))
        self.label_77.setText(_translate("q_dock", "<html><head/><body><p>Basis Abfluss [m<span style=\" vertical-align:super;\">3</span>/s]</p></body></html>"))
        self.label_83.setText(_translate("q_dock", "SF"))
        self.gi_zs.setToolTip(_translate("q_dock", "<html><head/><body><p align=\"justify\">Höhe der Überfall- bzw. Überluafkante</p><p align=\"justify\">über ser Sohle an Knoten, bei denen ein Überfall</p><p align=\"justify\">erfolgen kann [m]</p><p align=\"justify\">Bei Trapez- und unregelmäßigen Querschnitten </p><p align=\"justify\">wird die Profilhöhe als Überlaufkante angenommen.</p></body></html>"))
        self.label_84.setText(_translate("q_dock", "WSP limit"))
        self.wsp_ckm.setToolTip(_translate("q_dock", "<html><head/><body><p>Q = 2/3 * \'mue\' * (2*g) <span style=\" vertical-align:super;\">½ </span></p></body></html>"))
        self.wsp_hr0.setToolTip(_translate("q_dock", "<html><head/><body><p>Wassertand bis zu dem Anfangsrauigkeit gilt</p></body></html>"))
        self.gi_rni.setToolTip(_translate("q_dock", "<html><head/><body><p>Profil Typ 1: absolute Rauhigkeit [m]</p><p>Profil Typ 2,3,4: Rauhigkeitsbeiwert (Manning\'s n)</p><p>mit: Manning\'s n = 1/ks</p><p>ks = Stricklerbeiwert</p></body></html>"))
        self.label_76.setText(_translate("q_dock", "Anfangswassertiefe [m]"))
        self.label_78.setText(_translate("q_dock", "Höhe der Überfall"))
        self.label_79.setText(_translate("q_dock", "Abflussbeiwert \'mue\' (über Wehr)"))
        self.wsp_table.setToolTip(_translate("q_dock", "<html><head/><body><p>Wasserstand (n): wo Manning\'s N = (n) gilt </p></body></html>"))
        item = self.wsp_table.verticalHeaderItem(0)
        item.setText(_translate("q_dock", "1"))
        item = self.wsp_table.verticalHeaderItem(1)
        item.setText(_translate("q_dock", "2"))
        item = self.wsp_table.verticalHeaderItem(2)
        item.setText(_translate("q_dock", "3"))
        item = self.wsp_table.verticalHeaderItem(3)
        item.setText(_translate("q_dock", "4"))
        item = self.wsp_table.verticalHeaderItem(4)
        item.setText(_translate("q_dock", "5"))
        item = self.wsp_table.verticalHeaderItem(5)
        item.setText(_translate("q_dock", "6"))
        item = self.wsp_table.verticalHeaderItem(6)
        item.setText(_translate("q_dock", "7"))
        item = self.wsp_table.horizontalHeaderItem(0)
        item.setText(_translate("q_dock", "Wasserstand"))
        item = self.wsp_table.horizontalHeaderItem(1)
        item.setText(_translate("q_dock", "Manning"))
        self.qp_widget.setTabText(self.qp_widget.indexOf(self.wsp_rau_box2), _translate("q_dock", "WSP-Rauhigkeit Info"))
        self.label.setText(_translate("q_dock", "Knoten"))
        self.label_15.setText(_translate("q_dock", "Station [m]"))
        self.label_7.setText(_translate("q_dock", "Profil Name:"))
        self.label_3.setText(_translate("q_dock", "Anzahl der Punkte:"))
        self.label_2.setText(_translate("q_dock", "Aspect Ratio:"))


from pyqtgraph import PlotWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    q_dock = QtWidgets.QDockWidget()
    ui = Ui_q_dock()
    ui.setupUi(q_dock)
    q_dock.show()
    sys.exit(app.exec_())
