# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'nodedialog.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_nodeDialog(object):
    def setupUi(self, nodeDialog):
        nodeDialog.setObjectName("nodeDialog")
        nodeDialog.resize(548, 433)
        self.gridLayout = QtWidgets.QGridLayout(nodeDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.station_show = QtWidgets.QComboBox(nodeDialog)
        self.station_show.setMinimumSize(QtCore.QSize(100, 0))
        self.station_show.setObjectName("station_show")
        self.gridLayout.addWidget(self.station_show, 1, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(nodeDialog)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 6, 4, 1, 1)
        self.achse_show = QtWidgets.QLineEdit(nodeDialog)
        self.achse_show.setEnabled(False)
        self.achse_show.setObjectName("achse_show")
        self.gridLayout.addWidget(self.achse_show, 3, 2, 1, 5)
        self.label_2 = QtWidgets.QLabel(nodeDialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 5, 1, 1)
        self.label_5 = QtWidgets.QLabel(nodeDialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 1, 1, 6)
        self.start_station = QtWidgets.QLineEdit(nodeDialog)
        self.start_station.setObjectName("start_station")
        self.gridLayout.addWidget(self.start_station, 6, 2, 1, 1)
        self.edit_name = QtWidgets.QTableWidget(nodeDialog)
        self.edit_name.setObjectName("edit_name")
        self.edit_name.setColumnCount(4)
        self.edit_name.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.edit_name.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.edit_name.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.edit_name.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.edit_name.setHorizontalHeaderItem(3, item)
        self.gridLayout.addWidget(self.edit_name, 8, 0, 1, 7)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 9, 1, 1, 4)
        self.label_10 = QtWidgets.QLabel(nodeDialog)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 3, 1, 1, 1)
        self.ok = QtWidgets.QPushButton(nodeDialog)
        self.ok.setAutoDefault(False)
        self.ok.setObjectName("ok")
        self.gridLayout.addWidget(self.ok, 9, 5, 1, 1)
        self.label_6 = QtWidgets.QLabel(nodeDialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 1, 1, 3)
        self.gef = QtWidgets.QDoubleSpinBox(nodeDialog)
        self.gef.setDecimals(6)
        self.gef.setMinimum(-99.0)
        self.gef.setObjectName("gef")
        self.gridLayout.addWidget(self.gef, 7, 5, 1, 2)
        self.label_8 = QtWidgets.QLabel(nodeDialog)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 7, 1, 1, 1)
        self.deletenodes = QtWidgets.QCheckBox(nodeDialog)
        self.deletenodes.setChecked(True)
        self.deletenodes.setObjectName("deletenodes")
        self.gridLayout.addWidget(self.deletenodes, 5, 4, 1, 3)
        self.cancel = QtWidgets.QPushButton(nodeDialog)
        self.cancel.setAutoDefault(False)
        self.cancel.setObjectName("cancel")
        self.gridLayout.addWidget(self.cancel, 9, 6, 1, 1)
        self.label = QtWidgets.QLabel(nodeDialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(nodeDialog)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 7, 4, 1, 1)
        self.count = QtWidgets.QSpinBox(nodeDialog)
        self.count.setObjectName("count")
        self.gridLayout.addWidget(self.count, 6, 5, 1, 2)
        self.label_7 = QtWidgets.QLabel(nodeDialog)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 6, 1, 1, 1)
        self.end_station = QtWidgets.QLineEdit(nodeDialog)
        self.end_station.setObjectName("end_station")
        self.gridLayout.addWidget(self.end_station, 7, 2, 1, 1)
        self.node_show = QtWidgets.QLineEdit(nodeDialog)
        self.node_show.setEnabled(False)
        self.node_show.setObjectName("node_show")
        self.gridLayout.addWidget(self.node_show, 1, 6, 1, 1)
        self.id = QtWidgets.QLineEdit(nodeDialog)
        self.id.setEnabled(False)
        self.id.setObjectName("id")
        self.gridLayout.addWidget(self.id, 2, 6, 1, 1)
        self.label_11 = QtWidgets.QLabel(nodeDialog)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 2, 5, 1, 1)
        self.label_3 = QtWidgets.QLabel(nodeDialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 1, 1, 1)
        self.schnitt_show = QtWidgets.QLineEdit(nodeDialog)
        self.schnitt_show.setEnabled(False)
        self.schnitt_show.setMinimumSize(QtCore.QSize(150, 0))
        self.schnitt_show.setObjectName("schnitt_show")
        self.gridLayout.addWidget(self.schnitt_show, 2, 2, 1, 3)

        self.retranslateUi(nodeDialog)
        QtCore.QMetaObject.connectSlotsByName(nodeDialog)

    def retranslateUi(self, nodeDialog):
        _translate = QtCore.QCoreApplication.translate
        nodeDialog.setWindowTitle(_translate("nodeDialog", "Duplicate Schnitts"))
        self.label_9.setText(_translate("nodeDialog", "Schnitt Count"))
        self.label_2.setText(_translate("nodeDialog", "Knoten"))
        self.label_5.setText(_translate("nodeDialog", "Choose Station to duplicate:"))
        item = self.edit_name.horizontalHeaderItem(0)
        item.setText(_translate("nodeDialog", "Schnitt"))
        item = self.edit_name.horizontalHeaderItem(1)
        item.setText(_translate("nodeDialog", "Knoten"))
        item = self.edit_name.horizontalHeaderItem(2)
        item.setText(_translate("nodeDialog", "Station"))
        item = self.edit_name.horizontalHeaderItem(3)
        item.setText(_translate("nodeDialog", "Abstand"))
        self.label_10.setText(_translate("nodeDialog", "Achse"))
        self.ok.setText(_translate("nodeDialog", "OK"))
        self.label_6.setText(_translate("nodeDialog", "Define:"))
        self.label_8.setText(_translate("nodeDialog", "End Station"))
        self.deletenodes.setText(_translate("nodeDialog", "Zwischen liegenden Knoten Löschen"))
        self.cancel.setText(_translate("nodeDialog", "Cancel"))
        self.label.setText(_translate("nodeDialog", "Station"))
        self.label_4.setText(_translate("nodeDialog", "Gefälle"))
        self.label_7.setText(_translate("nodeDialog", "Start Station"))
        self.label_11.setText(_translate("nodeDialog", "Gew ID"))
        self.label_3.setText(_translate("nodeDialog", "Schnitt"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    nodeDialog = QtWidgets.QDialog()
    ui = Ui_nodeDialog()
    ui.setupUi(nodeDialog)
    nodeDialog.show()
    sys.exit(app.exec_())
