C     -*- fortran -*-
C     This file is autogenerated with f2py (version:2)
C     It contains Fortran 77 wrappers to fortran functions.

      subroutine f2pyinitRND(setupfunc)
      external setupfunc
      real HR0(10000)
      real HR(10000,7)
      real RNV(10000,7)
      common /RND/ HR0,HR,RNV
      call setupfunc(HR0,HR,RNV)
      end

      subroutine f2pyinitWAVE(setupfunc)
      external setupfunc
      real HWELLE(12,12000)
      real QWELLE(12,12000)
      integer ITUN
      integer IWEL
      real DTWEL
      integer NWEL
      integer KWEL(12)
      real TOT
      real STIME
      common /WAVE/ HWELLE,QWELLE,ITUN,IWEL,DTWEL,NWEL,KWEL,TOT,ST
     &IME
      call setupfunc(HWELLE,QWELLE,ITUN,IWEL,DTWEL,NWEL,KWEL,TOT,S
     &TIME)
      end

      subroutine f2pyinitRET1(setupfunc)
      external setupfunc
      integer NSPE(10000,20)
      integer NSP(10000,20)
      integer NRET
      integer NSTORE
      integer NWERTE(20)
      real ZETA(20)
      real DGRENZ(20)
      integer NVERB(10000)
      integer INDEX(10000)
      common /RET1/ NSPE,NSP,NRET,NSTORE,NWERTE,ZETA,DGRENZ,NVERB,
     &INDEX
      call setupfunc(NSPE,NSP,NRET,NSTORE,NWERTE,ZETA,DGRENZ,NVERB
     &,INDEX)
      end

      subroutine f2pyinitNAMES(setupfunc)
      external setupfunc
      integer IWEIRE(500)
      integer IGATEE(10)
      integer L1E(10000)
      integer NXJE(50,7)
      integer NUPE(51)
      integer KWELE(12)
      common /NAMES/ IWEIRE,IGATEE,L1E,NXJE,NUPE,KWELE
      call setupfunc(IWEIRE,IGATEE,L1E,NXJE,NUPE,KWELE)
      end

      subroutine f2pyinitRELAX(setupfunc)
      external setupfunc
      integer IRELAXFOR
      integer IRELAXBACK
      real DHZUL
      real DHRELZUL
      real DVRELZUL
      common /RELAX/ IRELAXFOR,IRELAXBACK,DHZUL,DHRELZUL,DVRELZUL
      call setupfunc(IRELAXFOR,IRELAXBACK,DHZUL,DHRELZUL,DVRELZUL)
      end

      subroutine f2pyinitTRAP(setupfunc)
      external setupfunc
      real ZTR(10000)
      real ZTL(10000)
      common /TRAP/ ZTR,ZTL
      call setupfunc(ZTR,ZTL)
      end

      subroutine f2pyinitQPARTS(setupfunc)
      external setupfunc
      real AHR0(10000)
      real AHR(10000,7)
      real WHR0(10000)
      real WHR(10000,7)
      real THR0(10000)
      real THR(10000,7)
      real QHR0(10000)
      real QHR(10000,7)
      common /QPARTS/ AHR0,AHR,WHR0,WHR,THR0,THR,QHR0,QHR
      call setupfunc(AHR0,AHR,WHR0,WHR,THR0,THR,QHR0,QHR)
      end

      subroutine f2pyinitREAD(setupfunc)
      external setupfunc
      integer ITERAT
      common /READ/ ITERAT
      call setupfunc(ITERAT)
      end

      subroutine f2pyinitLATER(setupfunc)
      external setupfunc
      integer LATINF
      integer L1(10000)
      real CLOSS(2,10000)
      integer LATCOM(10000)
      real GWFLOW(10000)
      common /LATER/ LATINF,L1,CLOSS,LATCOM,GWFLOW
      call setupfunc(LATINF,L1,CLOSS,LATCOM,GWFLOW)
      end

      subroutine f2pyinitXYKOORD(setupfunc)
      external setupfunc
      double precision XK(10000)
      double precision YK(10000)
      common /XYKOORD/ XK,YK
      call setupfunc(XK,YK)
      end

      subroutine f2pyinitCREEP(setupfunc)
      external setupfunc
      real GINITL(10,20000)
      common /CREEP/ GINITL
      call setupfunc(GINITL)
      end

      subroutine f2pyinitQF(setupfunc)
      external setupfunc
      real QFAK
      real QBAS
      common /QF/ QFAK,QBAS
      call setupfunc(QFAK,QBAS)
      end

      subroutine f2pyinitTBLE(setupfunc)
      external setupfunc
      real DYDQ(100)
      common /TBLE/ DYDQ
      call setupfunc(DYDQ)
      end

      subroutine f2pyinitSHPDBF(setupfunc)
      external setupfunc
      character*255 GEWSHP
      character*255 GEWDBF
      common /SHPDBF/ GEWSHP,GEWDBF
      call setupfunc(GEWSHP,GEWDBF)
      end

      subroutine f2pyinitIO(setupfunc)
      external setupfunc
      integer N5
      integer N6
      integer IN
      integer IOUT
      integer IGRAPH
      common /IO/ N5,N6,IN,IOUT,IGRAPH
      call setupfunc(N5,N6,IN,IOUT,IGRAPH)
      end

      subroutine f2pyinitKANTE(setupfunc)
      external setupfunc
      real ZKANTE(20)
      real BKANTE(20)
      real CMUEKANTE(20)
      real QGRKANTE(100,20)
      real ZSPO(100,20)
      integer JSPUW(20)
      common /KANTE/ ZKANTE,BKANTE,CMUEKANTE,QGRKANTE,ZSPO,JSPUW
      call setupfunc(ZKANTE,BKANTE,CMUEKANTE,QGRKANTE,ZSPO,JSPUW)
      end

      subroutine f2pyinitGANGLT(setupfunc)
      external setupfunc
      real TINC
      real TTEST
      real TPRIN
      common /GANGLT/ TINC,TTEST,TPRIN
      call setupfunc(TINC,TTEST,TPRIN)
      end

      subroutine f2pyinitWEHR(setupfunc)
      external setupfunc
      integer NWEIRS
      integer IWEIR(500)
      real HW(500)
      real BW(500)
      real WCO(500)
      real WNEI(500)
      real WNEIL(500)
      real WNEIR(500)
      integer IRAUS(500)
      real V2CO(500)
      real CCFAK(500)
      character WHQDAT(500,30)
      real WH(500,51)
      real WQ(500,51)
      common /WEHR/ NWEIRS,IWEIR,HW,BW,WCO,WNEI,WNEIL,WNEIR,IRAUS,
     &V2CO,CCFAK,WHQDAT,WH,WQ
      call setupfunc(NWEIRS,IWEIR,HW,BW,WCO,WNEI,WNEIL,WNEIR,IRAUS
     &,V2CO,CCFAK,WHQDAT,WH,WQ)
      end

      subroutine f2pyinitGEWID(setupfunc)
      external setupfunc
      integer ID(10000)
      common /GEWID/ ID
      call setupfunc(ID)
      end

      subroutine f2pyinitOVFBIL(setupfunc)
      external setupfunc
      character*6 OVFMOD
      integer NOVF(10000)
      integer IABOVF(10000)
      integer IOVF(10000)
      real QOFLSN(100)
      integer NOVFMX
      integer LIRE(10000)
      real OVFAN(10000)
      real OVFAUS(10000)
      integer IOVFSTAT(10000)
      real QOMAX(10000)
      real QREGEL(10000)
      real TOVFAN(10000)
      real TOVFAUS(10000)
      common /OVFBIL/ OVFMOD,NOVF,IABOVF,IOVF,QOFLSN,NOVFMX,LIRE,O
     &VFAN,OVFAUS,IOVFSTAT,QOMAX,QREGEL,TOVFAN,TOVFAUS
      call setupfunc(OVFMOD,NOVF,IABOVF,IOVF,QOFLSN,NOVFMX,LIRE,OV
     &FAN,OVFAUS,IOVFSTAT,QOMAX,QREGEL,TOVFAN,TOVFAUS)
      end

      subroutine f2pyinitGEOMTY(setupfunc)
      external setupfunc
      integer ITYPE(10000)
      real WIDTH(10000)
      real HEIT(10000)
      real ZO(10000)
      real ZS(10000)
      real RNI(10000)
      real RNIBAK(10000)
      real ZL(10000)
      real ZR(10000)
      common /GEOMTY/ ITYPE,WIDTH,HEIT,ZO,ZS,RNI,RNIBAK,ZL,ZR
      call setupfunc(ITYPE,WIDTH,HEIT,ZO,ZS,RNI,RNIBAK,ZL,ZR)
      end

      subroutine f2pyinitAQUI(setupfunc)
      external setupfunc
      real DGW(2,10000)
      integer IAQUI(2,10000)
      integer NAQ
      integer NGW
      real DTGW
      integer NGV
      real GHA(2,10000)
      real GS(2,10000)
      real TRANS(10)
      real POR(10)
      real BETA(10)
      real XGW(10000)
      common /AQUI/ DGW,IAQUI,NAQ,NGW,DTGW,NGV,GHA,GS,TRANS,POR,BE
     &TA,XGW
      call setupfunc(DGW,IAQUI,NAQ,NGW,DTGW,NGV,GHA,GS,TRANS,POR,B
     &ETA,XGW)
      end

      subroutine f2pyinitJUNC(setupfunc)
      external setupfunc
      character JUNNAM(50,40)
      common /JUNC/ JUNNAM
      call setupfunc(JUNNAM)
      end

      subroutine f2pyinitMODGAT(setupfunc)
      external setupfunc
      character GATMOD(10,1)
      common /MODGAT/ GATMOD
      call setupfunc(GATMOD)
      end

      subroutine f2pyinitQGAT(setupfunc)
      external setupfunc
      real AGA(10)
      real QGAMIN(10)
      real QGAMAX(10)
      real GATTOL(10)
      real RMUE(10)
      real GATMIN(10)
      real GATWSO(10)
      common /QGAT/ AGA,QGAMIN,QGAMAX,GATTOL,RMUE,GATMIN,GATWSO
      call setupfunc(AGA,QGAMIN,QGAMAX,GATTOL,RMUE,GATMIN,GATWSO)
      end

      subroutine f2pyinitQQGWSTAT(setupfunc)
      external setupfunc
      real QQMIN(10000)
      real QQMAX(10000)
      common /QQGWSTAT/ QQMIN,QQMAX
      call setupfunc(QQMIN,QQMAX)
      end

      subroutine f2pyinitURBAN(setupfunc)
      external setupfunc
      real SPK(100)
      real SPN(100)
      real ARED(100)
      real QBASA(100)
      real QBASE(100)
      real QMAX(100)
      common /URBAN/ SPK,SPN,ARED,QBASA,QBASE,QMAX
      call setupfunc(SPK,SPN,ARED,QBASA,QBASE,QMAX)
      end

      subroutine f2pyinitDOWNCO(setupfunc)
      external setupfunc
      real QDON(100)
      real YDON(100)
      integer IPTS
      integer IDOWN
      real A
      real B
      common /DOWNCO/ QDON,YDON,IPTS,IDOWN,A,B
      call setupfunc(QDON,YDON,IPTS,IDOWN,A,B)
      end

      subroutine f2pyinitKSTIME(setupfunc)
      external setupfunc
      character*6 KSTMOD
      integer KRAUT(10000)
      real TIMHKS(50)
      real FAKTKS(12000,3)
      real FAK(12000)
      common /KSTIME/ KSTMOD,KRAUT,TIMHKS,FAKTKS,FAK
      call setupfunc(KSTMOD,KRAUT,TIMHKS,FAKTKS,FAK)
      end

      subroutine f2pyinitCONV(setupfunc)
      external setupfunc
      real CONVEC
      common /CONV/ CONVEC
      call setupfunc(CONVEC)
      end

      subroutine f2pyinitTIB(setupfunc)
      external setupfunc
      real DT
      real TIME
      integer ITOTH
      integer ITOTM
      real TOTH
      integer JTIME
      common /TIB/ DT,TIME,ITOTH,ITOTM,TOTH,JTIME
      call setupfunc(DT,TIME,ITOTH,ITOTM,TOTH,JTIME)
      end

      subroutine f2pyinitGATES(setupfunc)
      external setupfunc
      integer IGATE(10)
      integer NGATES
      common /GATES/ IGATE,NGATES
      call setupfunc(IGATE,NGATES)
      end

      subroutine f2pyinitQLH(setupfunc)
      external setupfunc
      real QLI(12000,10000)
      common /QLH/ QLI
      call setupfunc(QLI)
      end

      subroutine f2pyinitDM(setupfunc)
      external setupfunc
      real U(10000)
      real D(10000)
      real H(10000)
      real Q(10000)
      real SF(10000)
      real XL(10000)
      real T(10000)
      real AREA(10000)
      real WP(10000)
      real DX(10000)
      real DPYH(10000)
      common /DM/ U,D,H,Q,SF,XL,T,AREA,WP,DX,DPYH
      call setupfunc(U,D,H,Q,SF,XL,T,AREA,WP,DX,DPYH)
      end

      subroutine f2pyinitGEOWP(setupfunc)
      external setupfunc
      real HWP(10000,51)
      integer IWP(10000,51)
      real RNFAK(10000,51)
      integer NNWP(10000)
      common /GEOWP/ HWP,IWP,RNFAK,NNWP
      call setupfunc(HWP,IWP,RNFAK,NNWP)
      end

      subroutine f2pyinitSTG(setupfunc)
      external setupfunc
      real DSTAGE(12000)
      common /STG/ DSTAGE
      call setupfunc(DSTAGE)
      end

      subroutine f2pyinitNUMB(setupfunc)
      external setupfunc
      integer LEAD
      common /NUMB/ LEAD
      call setupfunc(LEAD)
      end

      subroutine f2pyinitFLOWS(setupfunc)
      external setupfunc
      integer NQIN
      integer NUP(51)
      real QUP(12000,51)
      real CDOWN(12000)
      common /FLOWS/ NQIN,NUP,QUP,CDOWN
      call setupfunc(NQIN,NUP,QUP,CDOWN)
      end

      subroutine f2pyinitJUN(setupfunc)
      external setupfunc
      integer NJUNC
      integer NXJ(50,7)
      real XXL(50)
      real GAM(50,3)
      common /JUN/ NJUNC,NXJ,XXL,GAM
      call setupfunc(NJUNC,NXJ,XXL,GAM)
      end

      subroutine f2pyinitDATA(setupfunc)
      external setupfunc
      real BB
      real Z1
      real Z2
      real DIA
      real RN
      real S
      real YO
      common /DATA/ BB,Z1,Z2,DIA,RN,S,YO
      call setupfunc(BB,Z1,Z2,DIA,RN,S,YO)
      end

      subroutine f2pyinitSTUFF(setupfunc)
      external setupfunc
      integer NT
      integer NX
      integer LIST
      integer LLIST
      real GRAV
      real CKS(10000)
      integer NL
      integer INCRE
      integer IGATE2
      common /STUFF/ NT,NX,LIST,LLIST,GRAV,CKS,NL,INCRE,IGATE2
      call setupfunc(NT,NX,LIST,LLIST,GRAV,CKS,NL,INCRE,IGATE2)
      end

      subroutine f2pyinitREGEN(setupfunc)
      external setupfunc
      real SUMN
      common /REGEN/ SUMN
      call setupfunc(SUMN)
      end

      subroutine f2pyinitQDD(setupfunc)
      external setupfunc
      real QZERO(10000)
      real DZERO(10000)
      common /QDD/ QZERO,DZERO
      call setupfunc(QZERO,DZERO)
      end

      subroutine f2pyinitPRECIP(setupfunc)
      external setupfunc
      real PE(20000)
      integer NPREC
      real DTPREC
      common /PRECIP/ PE,NPREC,DTPREC
      call setupfunc(PE,NPREC,DTPREC)
      end

      subroutine f2pyinitERR(setupfunc)
      external setupfunc
      real TOL
      common /ERR/ TOL
      call setupfunc(TOL)
      end

      subroutine f2pyinitIRRSEC(setupfunc)
      external setupfunc
      integer ISEC
      integer NCO(10000)
      integer LAB(10000)
      real ASEC(10000,51)
      real TSEC(10000,51)
      real PSEC(10000,51)
      real CH2SEC(10000,51)
      real CHRSEC(10000,51)
      real QGRSEC(10000,51)
      common /IRRSEC/ ISEC,NCO,LAB,ASEC,TSEC,PSEC,CH2SEC,CHRSEC,QG
     &RSEC
      call setupfunc(ISEC,NCO,LAB,ASEC,TSEC,PSEC,CH2SEC,CHRSEC,QGR
     &SEC)
      end

      subroutine f2pyinitAB(setupfunc)
      external setupfunc
      integer IAB(10000)
      common /AB/ IAB
      call setupfunc(IAB)
      end

      subroutine f2pyinitVORSCH(setupfunc)
      external setupfunc
      integer IPRO
      common /VORSCH/ IPRO
      call setupfunc(IPRO)
      end

      subroutine f2pyinitBILAN(setupfunc)
      external setupfunc
      real QKNOTN(10000)
      real SQG(4,10000)
      real QOGES(20000)
      real QOSUM(10000)
      common /BILAN/ QKNOTN,SQG,QOGES,QOSUM
      call setupfunc(QKNOTN,SQG,QOGES,QOSUM)
      end

      subroutine f2pyinitBNDRY(setupfunc)
      external setupfunc
      real FLOW
      real DHH
      real DHT
      real ZSILL
      common /BNDRY/ FLOW,DHH,DHT,ZSILL
      call setupfunc(FLOW,DHH,DHT,ZSILL)
      end

      subroutine f2pyinitRETO(setupfunc)
      external setupfunc
      character RETOUT(20,30)
      common /RETO/ RETOUT
      call setupfunc(RETOUT)
      end


