# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'defaults.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_settings(object):
    def setupUi(self, settings):
        settings.setObjectName("settings")
        settings.resize(709, 646)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        settings.setFont(font)
        settings.setAutoFillBackground(True)
        self.gridLayout = QtWidgets.QGridLayout(settings)
        self.gridLayout.setObjectName("gridLayout")
        self.cancel = QtWidgets.QPushButton(settings)
        self.cancel.setObjectName("cancel")
        self.gridLayout.addWidget(self.cancel, 4, 6, 1, 1)
        self.saveDefault = QtWidgets.QCheckBox(settings)
        self.saveDefault.setObjectName("saveDefault")
        self.gridLayout.addWidget(self.saveDefault, 4, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(settings)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_35 = QtWidgets.QLabel(self.groupBox_5)
        self.label_35.setObjectName("label_35")
        self.gridLayout_7.addWidget(self.label_35, 9, 0, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.groupBox_5)
        self.label_31.setObjectName("label_31")
        self.gridLayout_7.addWidget(self.label_31, 3, 0, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.gridLayout_7.addWidget(self.label_33, 0, 0, 1, 2)
        self.label_27 = QtWidgets.QLabel(self.groupBox_5)
        self.label_27.setObjectName("label_27")
        self.gridLayout_7.addWidget(self.label_27, 1, 0, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.groupBox_5)
        self.label_32.setObjectName("label_32")
        self.gridLayout_7.addWidget(self.label_32, 2, 0, 1, 1)
        self.wpw = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.wpw.setProperty("value", 1.0)
        self.wpw.setObjectName("wpw")
        self.gridLayout_7.addWidget(self.wpw, 3, 1, 1, 1)
        self.eps = QtWidgets.QComboBox(self.groupBox_5)
        self.eps.setObjectName("eps")
        self.eps.addItem("")
        self.eps.addItem("")
        self.eps.addItem("")
        self.eps.addItem("")
        self.eps.addItem("")
        self.gridLayout_7.addWidget(self.eps, 8, 1, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.groupBox_5)
        self.label_34.setObjectName("label_34")
        self.gridLayout_7.addWidget(self.label_34, 8, 0, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.gridLayout_7.addWidget(self.label_29, 4, 0, 1, 2)
        self.wpc = QtWidgets.QPushButton(self.groupBox_5)
        self.wpc.setStyleSheet("QPushButton {\n"
"     background-color: rgb(0, 0, 0); border: 1px solid black;\n"
"}")
        self.wpc.setText("")
        self.wpc.setObjectName("wpc")
        self.gridLayout_7.addWidget(self.wpc, 1, 1, 1, 1)
        self.epw = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.epw.setProperty("value", 1.0)
        self.epw.setObjectName("epw")
        self.gridLayout_7.addWidget(self.epw, 9, 1, 1, 1)
        self.wps = QtWidgets.QComboBox(self.groupBox_5)
        self.wps.setObjectName("wps")
        self.wps.addItem("")
        self.wps.addItem("")
        self.wps.addItem("")
        self.wps.addItem("")
        self.wps.addItem("")
        self.gridLayout_7.addWidget(self.wps, 2, 1, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_5, 0, 1, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_17 = QtWidgets.QLabel(self.groupBox_2)
        self.label_17.setObjectName("label_17")
        self.gridLayout_6.addWidget(self.label_17, 7, 0, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.gridLayout_6.addWidget(self.label_28, 0, 0, 1, 2)
        self.label_24 = QtWidgets.QLabel(self.groupBox_2)
        self.label_24.setAutoFillBackground(True)
        self.label_24.setObjectName("label_24")
        self.gridLayout_6.addWidget(self.label_24, 8, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.groupBox_2)
        self.label_18.setObjectName("label_18")
        self.gridLayout_6.addWidget(self.label_18, 9, 0, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.groupBox_2)
        self.label_42.setObjectName("label_42")
        self.gridLayout_6.addWidget(self.label_42, 4, 0, 1, 1)
        self.lpc = QtWidgets.QPushButton(self.groupBox_2)
        self.lpc.setStyleSheet("QPushButton {\n"
"     background-color: rgb(0, 0, 0); border: 1px solid black;\n"
"}")
        self.lpc.setText("")
        self.lpc.setObjectName("lpc")
        self.gridLayout_6.addWidget(self.lpc, 1, 1, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.groupBox_2)
        self.label_26.setObjectName("label_26")
        self.gridLayout_6.addWidget(self.label_26, 10, 0, 1, 1)
        self.lb = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.lb.setProperty("value", 0.2)
        self.lb.setObjectName("lb")
        self.gridLayout_6.addWidget(self.lb, 11, 1, 1, 1)
        self.lfc = QtWidgets.QPushButton(self.groupBox_2)
        self.lfc.setStyleSheet("QPushButton {\n"
"     background-color: rgb(211, 140, 105); border: 1px solid black;\n"
"}")
        self.lfc.setText("")
        self.lfc.setObjectName("lfc")
        self.gridLayout_6.addWidget(self.lfc, 10, 1, 1, 1)
        self.lf = QtWidgets.QCheckBox(self.groupBox_2)
        self.lf.setText("")
        self.lf.setChecked(True)
        self.lf.setObjectName("lf")
        self.gridLayout_6.addWidget(self.lf, 9, 1, 1, 1)
        self.lg = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.lg.setDecimals(2)
        self.lg.setProperty("value", 2.0)
        self.lg.setObjectName("lg")
        self.gridLayout_6.addWidget(self.lg, 8, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.groupBox_2)
        self.label_16.setObjectName("label_16")
        self.gridLayout_6.addWidget(self.label_16, 6, 0, 1, 1)
        self.lc = QtWidgets.QPushButton(self.groupBox_2)
        self.lc.setStyleSheet("QPushButton {\n"
"     background-color: rgb(85, 0, 255); border: 1px solid black;\n"
"}")
        self.lc.setText("")
        self.lc.setObjectName("lc")
        self.gridLayout_6.addWidget(self.lc, 6, 1, 1, 1)
        self.ls = QtWidgets.QComboBox(self.groupBox_2)
        self.ls.setMaximumSize(QtCore.QSize(100, 16777215))
        self.ls.setObjectName("ls")
        self.ls.addItem("")
        self.ls.addItem("")
        self.ls.addItem("")
        self.ls.addItem("")
        self.ls.addItem("")
        self.ls.addItem("")
        self.ls.addItem("")
        self.gridLayout_6.addWidget(self.ls, 7, 1, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.groupBox_2)
        self.label_40.setObjectName("label_40")
        self.gridLayout_6.addWidget(self.label_40, 1, 0, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.groupBox_2)
        self.label_25.setObjectName("label_25")
        self.gridLayout_6.addWidget(self.label_25, 11, 0, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.groupBox_2)
        self.label_41.setObjectName("label_41")
        self.gridLayout_6.addWidget(self.label_41, 2, 0, 1, 1)
        self.lpw = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.lpw.setProperty("value", 1.0)
        self.lpw.setObjectName("lpw")
        self.gridLayout_6.addWidget(self.lpw, 4, 1, 1, 1)
        self.lps = QtWidgets.QComboBox(self.groupBox_2)
        self.lps.setObjectName("lps")
        self.lps.addItem("")
        self.lps.addItem("")
        self.lps.addItem("")
        self.lps.addItem("")
        self.lps.addItem("")
        self.gridLayout_6.addWidget(self.lps, 2, 1, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_3, 0, 0, 1, 7)
        self.ok = QtWidgets.QPushButton(settings)
        self.ok.setObjectName("ok")
        self.gridLayout.addWidget(self.ok, 4, 5, 1, 1)
        self.reset = QtWidgets.QPushButton(settings)
        self.reset.setObjectName("reset")
        self.gridLayout.addWidget(self.reset, 4, 4, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(settings)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.s3 = QtWidgets.QComboBox(self.groupBox_4)
        self.s3.setMaximumSize(QtCore.QSize(100, 16777215))
        self.s3.setObjectName("s3")
        self.s3.addItem("")
        self.s3.addItem("")
        self.s3.addItem("")
        self.s3.addItem("")
        self.s3.addItem("")
        self.s3.addItem("")
        self.s3.addItem("")
        self.gridLayout_3.addWidget(self.s3, 3, 3, 1, 1)
        self.s7 = QtWidgets.QComboBox(self.groupBox_4)
        self.s7.setMaximumSize(QtCore.QSize(100, 16777215))
        self.s7.setObjectName("s7")
        self.s7.addItem("")
        self.s7.addItem("")
        self.s7.addItem("")
        self.s7.addItem("")
        self.s7.addItem("")
        self.s7.addItem("")
        self.s7.addItem("")
        self.gridLayout_3.addWidget(self.s7, 7, 3, 1, 1)
        self.v3 = QtWidgets.QCheckBox(self.groupBox_4)
        self.v3.setText("")
        self.v3.setChecked(True)
        self.v3.setObjectName("v3")
        self.gridLayout_3.addWidget(self.v3, 3, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_4)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 9, 0, 1, 1)
        self.v6 = QtWidgets.QCheckBox(self.groupBox_4)
        self.v6.setText("")
        self.v6.setChecked(True)
        self.v6.setObjectName("v6")
        self.gridLayout_3.addWidget(self.v6, 6, 1, 1, 1)
        self.g5 = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.g5.setProperty("value", 9.0)
        self.g5.setObjectName("g5")
        self.gridLayout_3.addWidget(self.g5, 5, 4, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox_4)
        self.label_14.setAutoFillBackground(True)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 0, 0, 1, 1)
        self.g6 = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.g6.setProperty("value", 10.0)
        self.g6.setObjectName("g6")
        self.gridLayout_3.addWidget(self.g6, 6, 4, 1, 1)
        self.v8 = QtWidgets.QCheckBox(self.groupBox_4)
        self.v8.setText("")
        self.v8.setChecked(True)
        self.v8.setObjectName("v8")
        self.gridLayout_3.addWidget(self.v8, 8, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_4)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 1, 0, 1, 1)
        self.c3 = QtWidgets.QPushButton(self.groupBox_4)
        self.c3.setStyleSheet("QPushButton {\n"
"     background-color: rgb(0, 0, 0); border: 1px solid black;\n"
"}")
        self.c3.setText("")
        self.c3.setObjectName("c3")
        self.gridLayout_3.addWidget(self.c3, 3, 2, 1, 1)
        self.v1 = QtWidgets.QCheckBox(self.groupBox_4)
        self.v1.setText("")
        self.v1.setChecked(True)
        self.v1.setObjectName("v1")
        self.gridLayout_3.addWidget(self.v1, 1, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.groupBox_4)
        self.label_20.setAutoFillBackground(True)
        self.label_20.setObjectName("label_20")
        self.gridLayout_3.addWidget(self.label_20, 0, 2, 1, 1)
        self.c4 = QtWidgets.QPushButton(self.groupBox_4)
        self.c4.setStyleSheet("QPushButton {\n"
"     background-color: rgb(0, 0, 255); border: 1px solid black;\n"
"}")
        self.c4.setText("")
        self.c4.setObjectName("c4")
        self.gridLayout_3.addWidget(self.c4, 4, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_4)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 6, 0, 1, 1)
        self.g3 = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.g3.setProperty("value", 6.0)
        self.g3.setObjectName("g3")
        self.gridLayout_3.addWidget(self.g3, 3, 4, 1, 1)
        self.c8 = QtWidgets.QPushButton(self.groupBox_4)
        self.c8.setStyleSheet("QPushButton {\n"
"     background-color: #3cbaa2; border: 1px solid black;\n"
"}")
        self.c8.setText("")
        self.c8.setObjectName("c8")
        self.gridLayout_3.addWidget(self.c8, 8, 2, 1, 1)
        self.s2 = QtWidgets.QComboBox(self.groupBox_4)
        self.s2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.s2.setObjectName("s2")
        self.s2.addItem("")
        self.s2.addItem("")
        self.s2.addItem("")
        self.s2.addItem("")
        self.s2.addItem("")
        self.s2.addItem("")
        self.s2.addItem("")
        self.gridLayout_3.addWidget(self.s2, 2, 3, 1, 1)
        self.v4 = QtWidgets.QCheckBox(self.groupBox_4)
        self.v4.setText("")
        self.v4.setChecked(True)
        self.v4.setObjectName("v4")
        self.gridLayout_3.addWidget(self.v4, 4, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.groupBox_4)
        self.label_19.setAutoFillBackground(True)
        self.label_19.setObjectName("label_19")
        self.gridLayout_3.addWidget(self.label_19, 0, 1, 1, 1)
        self.g7 = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.g7.setProperty("value", 10.0)
        self.g7.setObjectName("g7")
        self.gridLayout_3.addWidget(self.g7, 7, 4, 1, 1)
        self.v2 = QtWidgets.QCheckBox(self.groupBox_4)
        self.v2.setText("")
        self.v2.setChecked(True)
        self.v2.setObjectName("v2")
        self.gridLayout_3.addWidget(self.v2, 2, 1, 1, 1)
        self.c2 = QtWidgets.QPushButton(self.groupBox_4)
        self.c2.setStyleSheet("QPushButton {\n"
"     background-color: rgb(255, 0, 0); border: 1px solid black;\n"
"}")
        self.c2.setText("")
        self.c2.setObjectName("c2")
        self.gridLayout_3.addWidget(self.c2, 2, 2, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.groupBox_4)
        self.label_22.setAutoFillBackground(True)
        self.label_22.setObjectName("label_22")
        self.gridLayout_3.addWidget(self.label_22, 0, 4, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_4)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 5, 0, 1, 1)
        self.g9 = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.g9.setProperty("value", 9.0)
        self.g9.setObjectName("g9")
        self.gridLayout_3.addWidget(self.g9, 9, 4, 1, 1)
        self.c1 = QtWidgets.QPushButton(self.groupBox_4)
        self.c1.setStyleSheet("QPushButton {\n"
"     background-color: rgb(0, 0, 0); border: 1px solid black;\n"
"}")
        self.c1.setText("")
        self.c1.setObjectName("c1")
        self.gridLayout_3.addWidget(self.c1, 1, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_4)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 4, 0, 1, 1)
        self.s4 = QtWidgets.QComboBox(self.groupBox_4)
        self.s4.setMaximumSize(QtCore.QSize(100, 16777215))
        self.s4.setObjectName("s4")
        self.s4.addItem("")
        self.s4.addItem("")
        self.s4.addItem("")
        self.s4.addItem("")
        self.s4.addItem("")
        self.s4.addItem("")
        self.s4.addItem("")
        self.gridLayout_3.addWidget(self.s4, 4, 3, 1, 1)
        self.c6 = QtWidgets.QPushButton(self.groupBox_4)
        self.c6.setStyleSheet("QPushButton {\n"
"     background-color: rgb(0, 170, 127); border: 1px solid black;\n"
"}")
        self.c6.setText("")
        self.c6.setObjectName("c6")
        self.gridLayout_3.addWidget(self.c6, 6, 2, 1, 1)
        self.g8 = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.g8.setProperty("value", 10.0)
        self.g8.setObjectName("g8")
        self.gridLayout_3.addWidget(self.g8, 8, 4, 1, 1)
        self.c9 = QtWidgets.QPushButton(self.groupBox_4)
        self.c9.setStyleSheet("QPushButton {\n"
"     background-color: rgb(0, 0, 255); border: 1px solid black;\n"
"}")
        self.c9.setText("")
        self.c9.setObjectName("c9")
        self.gridLayout_3.addWidget(self.c9, 9, 2, 1, 1)
        self.c5 = QtWidgets.QPushButton(self.groupBox_4)
        self.c5.setStyleSheet("QPushButton {\n"
"     background-color: rgb(0, 0, 0); border: 1px solid black;\n"
"}")
        self.c5.setText("")
        self.c5.setObjectName("c5")
        self.gridLayout_3.addWidget(self.c5, 5, 2, 1, 1)
        self.s5 = QtWidgets.QComboBox(self.groupBox_4)
        self.s5.setMaximumSize(QtCore.QSize(100, 16777215))
        self.s5.setObjectName("s5")
        self.s5.addItem("")
        self.s5.addItem("")
        self.s5.addItem("")
        self.s5.addItem("")
        self.s5.addItem("")
        self.s5.addItem("")
        self.s5.addItem("")
        self.gridLayout_3.addWidget(self.s5, 5, 3, 1, 1)
        self.g2 = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.g2.setProperty("value", 6.0)
        self.g2.setObjectName("g2")
        self.gridLayout_3.addWidget(self.g2, 2, 4, 1, 1)
        self.v5 = QtWidgets.QCheckBox(self.groupBox_4)
        self.v5.setText("")
        self.v5.setChecked(True)
        self.v5.setObjectName("v5")
        self.gridLayout_3.addWidget(self.v5, 5, 1, 1, 1)
        self.s9 = QtWidgets.QComboBox(self.groupBox_4)
        self.s9.setMaximumSize(QtCore.QSize(100, 16777215))
        self.s9.setObjectName("s9")
        self.s9.addItem("")
        self.s9.addItem("")
        self.s9.addItem("")
        self.s9.addItem("")
        self.s9.addItem("")
        self.s9.addItem("")
        self.s9.addItem("")
        self.gridLayout_3.addWidget(self.s9, 9, 3, 1, 1)
        self.g1 = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.g1.setDecimals(2)
        self.g1.setProperty("value", 6.0)
        self.g1.setObjectName("g1")
        self.gridLayout_3.addWidget(self.g1, 1, 4, 1, 1)
        self.c7 = QtWidgets.QPushButton(self.groupBox_4)
        self.c7.setStyleSheet("QPushButton {\n"
"     background-color: #3cbaa2; border: 1px solid black;\n"
"}")
        self.c7.setText("")
        self.c7.setObjectName("c7")
        self.gridLayout_3.addWidget(self.c7, 7, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_4)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 7, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_4)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 2, 0, 1, 1)
        self.v9 = QtWidgets.QCheckBox(self.groupBox_4)
        self.v9.setText("")
        self.v9.setChecked(True)
        self.v9.setObjectName("v9")
        self.gridLayout_3.addWidget(self.v9, 9, 1, 1, 1)
        self.s6 = QtWidgets.QComboBox(self.groupBox_4)
        self.s6.setMaximumSize(QtCore.QSize(100, 16777215))
        self.s6.setObjectName("s6")
        self.s6.addItem("")
        self.s6.addItem("")
        self.s6.addItem("")
        self.s6.addItem("")
        self.s6.addItem("")
        self.s6.addItem("")
        self.s6.addItem("")
        self.gridLayout_3.addWidget(self.s6, 6, 3, 1, 1)
        self.g4 = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.g4.setProperty("value", 6.0)
        self.g4.setObjectName("g4")
        self.gridLayout_3.addWidget(self.g4, 4, 4, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_4)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 8, 0, 1, 1)
        self.v7 = QtWidgets.QCheckBox(self.groupBox_4)
        self.v7.setText("")
        self.v7.setChecked(True)
        self.v7.setObjectName("v7")
        self.gridLayout_3.addWidget(self.v7, 7, 1, 1, 1)
        self.s1 = QtWidgets.QComboBox(self.groupBox_4)
        self.s1.setMaximumSize(QtCore.QSize(100, 16777215))
        self.s1.setObjectName("s1")
        self.s1.addItem("")
        self.s1.addItem("")
        self.s1.addItem("")
        self.s1.addItem("")
        self.s1.addItem("")
        self.s1.addItem("")
        self.s1.addItem("")
        self.gridLayout_3.addWidget(self.s1, 1, 3, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.groupBox_4)
        self.label_21.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_21.setAutoFillBackground(True)
        self.label_21.setObjectName("label_21")
        self.gridLayout_3.addWidget(self.label_21, 0, 3, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_4)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 3, 0, 1, 1)
        self.s8 = QtWidgets.QComboBox(self.groupBox_4)
        self.s8.setMaximumSize(QtCore.QSize(100, 16777215))
        self.s8.setObjectName("s8")
        self.s8.addItem("")
        self.s8.addItem("")
        self.s8.addItem("")
        self.s8.addItem("")
        self.s8.addItem("")
        self.s8.addItem("")
        self.s8.addItem("")
        self.gridLayout_3.addWidget(self.s8, 8, 3, 1, 1)
        self.gridLayout.addWidget(self.groupBox_4, 2, 3, 1, 4)
        self.groupBox = QtWidgets.QGroupBox(settings)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.qb = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.qb.setProperty("value", 1.0)
        self.qb.setObjectName("qb")
        self.gridLayout_2.addWidget(self.qb, 3, 5, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 4, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 1, 4, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.groupBox)
        self.label_45.setObjectName("label_45")
        self.gridLayout_2.addWidget(self.label_45, 2, 0, 1, 1)
        self.qc = QtWidgets.QPushButton(self.groupBox)
        self.qc.setStyleSheet("QPushButton {\n"
"     background-color: rgb(255, 0, 0); border: 1px solid black;\n"
"}")
        self.qc.setText("")
        self.qc.setObjectName("qc")
        self.gridLayout_2.addWidget(self.qc, 4, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.groupBox)
        self.label_23.setAutoFillBackground(True)
        self.label_23.setObjectName("label_23")
        self.gridLayout_2.addWidget(self.label_23, 0, 4, 1, 1)
        self.qpw = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.qpw.setProperty("value", 1.0)
        self.qpw.setObjectName("qpw")
        self.gridLayout_2.addWidget(self.qpw, 2, 1, 1, 1)
        self.qf = QtWidgets.QCheckBox(self.groupBox)
        self.qf.setText("")
        self.qf.setChecked(True)
        self.qf.setObjectName("qf")
        self.gridLayout_2.addWidget(self.qf, 1, 5, 1, 1)
        self.qfc = QtWidgets.QPushButton(self.groupBox)
        self.qfc.setStyleSheet("QPushButton {\n"
"     background-color: rgb(211, 140, 105); border: 1px solid black;\n"
"}")
        self.qfc.setText("")
        self.qfc.setObjectName("qfc")
        self.gridLayout_2.addWidget(self.qfc, 2, 5, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.groupBox)
        self.label_44.setObjectName("label_44")
        self.gridLayout_2.addWidget(self.label_44, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 3, 0, 1, 1)
        self.qps = QtWidgets.QComboBox(self.groupBox)
        self.qps.setObjectName("qps")
        self.qps.addItem("")
        self.qps.addItem("")
        self.qps.addItem("")
        self.qps.addItem("")
        self.qps.addItem("")
        self.gridLayout_2.addWidget(self.qps, 1, 1, 1, 1)
        self.qs = QtWidgets.QComboBox(self.groupBox)
        self.qs.setMaximumSize(QtCore.QSize(100, 16777215))
        self.qs.setObjectName("qs")
        self.qs.addItem("")
        self.qs.addItem("")
        self.qs.addItem("")
        self.qs.addItem("")
        self.qs.addItem("")
        self.qs.addItem("")
        self.qs.addItem("")
        self.gridLayout_2.addWidget(self.qs, 3, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 4, 0, 1, 1)
        self.qg = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.qg.setDecimals(2)
        self.qg.setProperty("value", 2.0)
        self.qg.setObjectName("qg")
        self.gridLayout_2.addWidget(self.qg, 0, 5, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 3, 4, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.groupBox)
        self.label_43.setObjectName("label_43")
        self.gridLayout_2.addWidget(self.label_43, 0, 0, 1, 1)
        self.qpc = QtWidgets.QPushButton(self.groupBox)
        self.qpc.setStyleSheet("QPushButton {\n"
"     background-color: rgb(0, 0, 0); border: 1px solid black;\n"
"}")
        self.qpc.setText("")
        self.qpc.setObjectName("qpc")
        self.gridLayout_2.addWidget(self.qpc, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 2, 0, 1, 3)

        self.retranslateUi(settings)
        self.eps.setCurrentIndex(1)
        self.ls.setCurrentIndex(3)
        self.s3.setCurrentIndex(2)
        self.s7.setCurrentIndex(6)
        self.s2.setCurrentIndex(1)
        self.s4.setCurrentIndex(3)
        self.s5.setCurrentIndex(4)
        self.s9.setCurrentIndex(5)
        self.s6.setCurrentIndex(6)
        self.s8.setCurrentIndex(6)
        self.qs.setCurrentIndex(5)
        QtCore.QMetaObject.connectSlotsByName(settings)

    def retranslateUi(self, settings):
        _translate = QtCore.QCoreApplication.translate
        settings.setWindowTitle(_translate("settings", "Plot Einstellungen"))
        self.cancel.setText(_translate("settings", "cancel"))
        self.saveDefault.setText(_translate("settings", "Save for all Projects"))
        self.groupBox_3.setTitle(_translate("settings", "Längsschnitt"))
        self.label_35.setText(_translate("settings", "PenWidth"))
        self.label_31.setText(_translate("settings", "PenWidth"))
        self.label_33.setText(_translate("settings", "Wasserstand"))
        self.label_27.setText(_translate("settings", "PenColor"))
        self.label_32.setText(_translate("settings", "PenStyle"))
        self.eps.setItemText(0, _translate("settings", "Solid"))
        self.eps.setItemText(1, _translate("settings", "Dash"))
        self.eps.setItemText(2, _translate("settings", "Dot"))
        self.eps.setItemText(3, _translate("settings", "Dash-Dot"))
        self.eps.setItemText(4, _translate("settings", "Dash-Dot-Dot"))
        self.label_34.setText(_translate("settings", "PenStyle"))
        self.label_29.setText(_translate("settings", "Energielinie"))
        self.wps.setItemText(0, _translate("settings", "Solid"))
        self.wps.setItemText(1, _translate("settings", "Dash"))
        self.wps.setItemText(2, _translate("settings", "Dot"))
        self.wps.setItemText(3, _translate("settings", "Dash-Dot"))
        self.wps.setItemText(4, _translate("settings", "Dash-Dot-Dot"))
        self.label_17.setText(_translate("settings", "Symbol"))
        self.label_28.setText(_translate("settings", "Sohle"))
        self.label_24.setText(_translate("settings", "SymbolSize"))
        self.label_18.setText(_translate("settings", "Fill"))
        self.label_42.setText(_translate("settings", "PenWidth"))
        self.label_26.setText(_translate("settings", "FillColor"))
        self.label_16.setText(_translate("settings", "SymbolColor"))
        self.ls.setItemText(0, _translate("settings", "Hexagon"))
        self.ls.setItemText(1, _translate("settings", "Square"))
        self.ls.setItemText(2, _translate("settings", "Pentagon"))
        self.ls.setItemText(3, _translate("settings", "Circle"))
        self.ls.setItemText(4, _translate("settings", "Plus"))
        self.ls.setItemText(5, _translate("settings", "Diamond"))
        self.ls.setItemText(6, _translate("settings", "Star"))
        self.label_40.setText(_translate("settings", "PenColor"))
        self.label_25.setText(_translate("settings", "Plot Bottom[m]"))
        self.label_41.setText(_translate("settings", "PenStyle"))
        self.lps.setItemText(0, _translate("settings", "Solid"))
        self.lps.setItemText(1, _translate("settings", "Dash"))
        self.lps.setItemText(2, _translate("settings", "Dot"))
        self.lps.setItemText(3, _translate("settings", "Dash-Dot"))
        self.lps.setItemText(4, _translate("settings", "Dash-Dot-Dot"))
        self.ok.setText(_translate("settings", "update"))
        self.reset.setText(_translate("settings", "reset"))
        self.groupBox_4.setTitle(_translate("settings", "Lageplan"))
        self.s3.setItemText(0, _translate("settings", "Hexagon"))
        self.s3.setItemText(1, _translate("settings", "Square"))
        self.s3.setItemText(2, _translate("settings", "Pentagon"))
        self.s3.setItemText(3, _translate("settings", "Circle"))
        self.s3.setItemText(4, _translate("settings", "Plus"))
        self.s3.setItemText(5, _translate("settings", "Diamond"))
        self.s3.setItemText(6, _translate("settings", "Star"))
        self.s7.setItemText(0, _translate("settings", "Hexagon"))
        self.s7.setItemText(1, _translate("settings", "Square"))
        self.s7.setItemText(2, _translate("settings", "Pentagon"))
        self.s7.setItemText(3, _translate("settings", "Circle"))
        self.s7.setItemText(4, _translate("settings", "Plus"))
        self.s7.setItemText(5, _translate("settings", "Diamond"))
        self.s7.setItemText(6, _translate("settings", "Star"))
        self.label_13.setText(_translate("settings", "ITYP9"))
        self.label_14.setText(_translate("settings", "Type"))
        self.label_5.setText(_translate("settings", "ITYP1"))
        self.label_20.setText(_translate("settings", "SymbolColor"))
        self.label_10.setText(_translate("settings", "ITYP6"))
        self.s2.setItemText(0, _translate("settings", "Hexagon"))
        self.s2.setItemText(1, _translate("settings", "Square"))
        self.s2.setItemText(2, _translate("settings", "Pentagon"))
        self.s2.setItemText(3, _translate("settings", "Circle"))
        self.s2.setItemText(4, _translate("settings", "Plus"))
        self.s2.setItemText(5, _translate("settings", "Diamond"))
        self.s2.setItemText(6, _translate("settings", "Star"))
        self.label_19.setText(_translate("settings", "Visible"))
        self.label_22.setText(_translate("settings", "SymbolSize"))
        self.label_9.setText(_translate("settings", "ITYP5"))
        self.label_8.setText(_translate("settings", "ITYP4"))
        self.s4.setItemText(0, _translate("settings", "Hexagon"))
        self.s4.setItemText(1, _translate("settings", "Square"))
        self.s4.setItemText(2, _translate("settings", "Pentagon"))
        self.s4.setItemText(3, _translate("settings", "Circle"))
        self.s4.setItemText(4, _translate("settings", "Plus"))
        self.s4.setItemText(5, _translate("settings", "Diamond"))
        self.s4.setItemText(6, _translate("settings", "Star"))
        self.s5.setItemText(0, _translate("settings", "Hexagon"))
        self.s5.setItemText(1, _translate("settings", "Square"))
        self.s5.setItemText(2, _translate("settings", "Pentagon"))
        self.s5.setItemText(3, _translate("settings", "Circle"))
        self.s5.setItemText(4, _translate("settings", "Plus"))
        self.s5.setItemText(5, _translate("settings", "Diamond"))
        self.s5.setItemText(6, _translate("settings", "Star"))
        self.s9.setCurrentText(_translate("settings", "Diamond"))
        self.s9.setItemText(0, _translate("settings", "Hexagon"))
        self.s9.setItemText(1, _translate("settings", "Square"))
        self.s9.setItemText(2, _translate("settings", "Pentagon"))
        self.s9.setItemText(3, _translate("settings", "Circle"))
        self.s9.setItemText(4, _translate("settings", "Plus"))
        self.s9.setItemText(5, _translate("settings", "Diamond"))
        self.s9.setItemText(6, _translate("settings", "Star"))
        self.label_11.setText(_translate("settings", "ITYP7"))
        self.label_6.setText(_translate("settings", "ITYP2"))
        self.s6.setItemText(0, _translate("settings", "Hexagon"))
        self.s6.setItemText(1, _translate("settings", "Square"))
        self.s6.setItemText(2, _translate("settings", "Pentagon"))
        self.s6.setItemText(3, _translate("settings", "Circle"))
        self.s6.setItemText(4, _translate("settings", "Plus"))
        self.s6.setItemText(5, _translate("settings", "Diamond"))
        self.s6.setItemText(6, _translate("settings", "Star"))
        self.label_12.setText(_translate("settings", "ITYP8"))
        self.s1.setItemText(0, _translate("settings", "Hexagon"))
        self.s1.setItemText(1, _translate("settings", "Square"))
        self.s1.setItemText(2, _translate("settings", "Pentagon"))
        self.s1.setItemText(3, _translate("settings", "Circle"))
        self.s1.setItemText(4, _translate("settings", "Plus"))
        self.s1.setItemText(5, _translate("settings", "Diamond"))
        self.s1.setItemText(6, _translate("settings", "Star"))
        self.label_21.setText(_translate("settings", "Symbol"))
        self.label_7.setText(_translate("settings", "ITYP3"))
        self.s8.setItemText(0, _translate("settings", "Hexagon"))
        self.s8.setItemText(1, _translate("settings", "Square"))
        self.s8.setItemText(2, _translate("settings", "Pentagon"))
        self.s8.setItemText(3, _translate("settings", "Circle"))
        self.s8.setItemText(4, _translate("settings", "Plus"))
        self.s8.setItemText(5, _translate("settings", "Diamond"))
        self.s8.setItemText(6, _translate("settings", "Star"))
        self.groupBox.setTitle(_translate("settings", "Querschnitt"))
        self.label_3.setText(_translate("settings", "FillColor"))
        self.label_15.setText(_translate("settings", "Fill"))
        self.label_45.setText(_translate("settings", "PenWidth"))
        self.label_23.setText(_translate("settings", "SymbolSize"))
        self.label_44.setText(_translate("settings", "PenStyle"))
        self.label.setText(_translate("settings", "Symbol"))
        self.qps.setItemText(0, _translate("settings", "Solid"))
        self.qps.setItemText(1, _translate("settings", "Dash"))
        self.qps.setItemText(2, _translate("settings", "Dot"))
        self.qps.setItemText(3, _translate("settings", "Dash-Dot"))
        self.qps.setItemText(4, _translate("settings", "Dash-Dot-Dot"))
        self.qs.setItemText(0, _translate("settings", "Hexagon"))
        self.qs.setItemText(1, _translate("settings", "Square"))
        self.qs.setItemText(2, _translate("settings", "Pentagon"))
        self.qs.setItemText(3, _translate("settings", "Circle"))
        self.qs.setItemText(4, _translate("settings", "Plus"))
        self.qs.setItemText(5, _translate("settings", "Diamond"))
        self.qs.setItemText(6, _translate("settings", "Star"))
        self.label_2.setText(_translate("settings", "SymbolColor"))
        self.label_4.setText(_translate("settings", "Plot Bottom[m]"))
        self.label_43.setText(_translate("settings", "PenColor"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    settings = QtWidgets.QWidget()
    ui = Ui_settings()
    ui.setupUi(settings)
    settings.show()
    sys.exit(app.exec_())
