# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'inflowdat.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_inflowdat(object):
    def setupUi(self, inflowdat):
        inflowdat.setObjectName("inflowdat")
        inflowdat.resize(654, 509)
        self.gridLayout = QtWidgets.QGridLayout(inflowdat)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(inflowdat)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.einqt = QtWidgets.QTableWidget(self.groupBox)
        self.einqt.setObjectName("einqt")
        self.einqt.setColumnCount(1)
        self.einqt.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.einqt.setHorizontalHeaderItem(0, item)
        self.einqt.horizontalHeader().setCascadingSectionResizes(False)
        self.einqt.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_2.addWidget(self.einqt, 1, 5, 9, 2)
        self.einbq = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.einbq.setMaximum(1000000.0)
        self.einbq.setObjectName("einbq")
        self.gridLayout_2.addWidget(self.einbq, 2, 1, 1, 2)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 6, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.qori = QtWidgets.QRadioButton(self.groupBox)
        self.qori.setChecked(True)
        self.qori.setObjectName("qori")
        self.qchoose = QtWidgets.QButtonGroup(inflowdat)
        self.qchoose.setObjectName("qchoose")
        self.qchoose.addButton(self.qori)
        self.gridLayout_2.addWidget(self.qori, 0, 5, 1, 1)
        self.einstat = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.einstat.setMaximum(1000000.0)
        self.einstat.setObjectName("einstat")
        self.gridLayout_2.addWidget(self.einstat, 1, 1, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 8, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 3, 0, 1, 1)
        self.eincount = QtWidgets.QSpinBox(self.groupBox)
        self.eincount.setMinimum(-100000)
        self.eincount.setMaximum(100000)
        self.eincount.setObjectName("eincount")
        self.gridLayout_2.addWidget(self.eincount, 5, 1, 1, 2)
        self.einbrowse = QtWidgets.QToolButton(self.groupBox)
        self.einbrowse.setObjectName("einbrowse")
        self.gridLayout_2.addWidget(self.einbrowse, 0, 2, 1, 1)
        self.eindat = QtWidgets.QLineEdit(self.groupBox)
        self.eindat.setObjectName("eindat")
        self.gridLayout_2.addWidget(self.eindat, 0, 1, 1, 1)
        self.eintext = QtWidgets.QTextBrowser(self.groupBox)
        self.eintext.setMaximumSize(QtCore.QSize(16777215, 70))
        self.eintext.setObjectName("eintext")
        self.gridLayout_2.addWidget(self.eintext, 3, 1, 1, 2)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.groupBox)
        self.buttonBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close|QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_2.addWidget(self.buttonBox, 9, 0, 1, 3)
        self.qfak = QtWidgets.QRadioButton(self.groupBox)
        self.qfak.setChecked(False)
        self.qfak.setObjectName("qfak")
        self.qchoose.addButton(self.qfak)
        self.gridLayout_2.addWidget(self.qfak, 0, 6, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 5, 0, 1, 1)
        self.eindt = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.eindt.setMaximum(1000000.0)
        self.eindt.setObjectName("eindt")
        self.gridLayout_2.addWidget(self.eindt, 6, 1, 1, 2)
        self.graphicsView = PlotWidget(self.groupBox)
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout_2.addWidget(self.graphicsView, 7, 0, 2, 3)
        self.gridLayout.addWidget(self.groupBox, 9, 4, 1, 1)

        self.retranslateUi(inflowdat)
        self.buttonBox.accepted.connect(inflowdat.accept)
        self.buttonBox.rejected.connect(inflowdat.reject)
        QtCore.QMetaObject.connectSlotsByName(inflowdat)

    def retranslateUi(self, inflowdat):
        _translate = QtCore.QCoreApplication.translate
        inflowdat.setWindowTitle(_translate("inflowdat", "Zufluss Welle"))
        self.label.setText(_translate("inflowdat", "Datei"))
        item = self.einqt.horizontalHeaderItem(0)
        item.setText(_translate("inflowdat", "Q"))
        self.label_6.setText(_translate("inflowdat", "Zeitschritt [h]"))
        self.label_2.setText(_translate("inflowdat", "Station"))
        self.qori.setText(_translate("inflowdat", "Q"))
        self.label_3.setText(_translate("inflowdat", "Basis Abfluss"))
        self.label_4.setText(_translate("inflowdat", "Kommentar:"))
        self.einbrowse.setText(_translate("inflowdat", "..."))
        self.qfak.setText(_translate("inflowdat", "Q-Faktor"))
        self.label_5.setText(_translate("inflowdat", "Anzahl"))


from pyqtgraph import PlotWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    inflowdat = QtWidgets.QDialog()
    ui = Ui_inflowdat()
    ui.setupUi(inflowdat)
    inflowdat.show()
    sys.exit(app.exec_())
