# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'nodegenDialog.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_nodegenDialog(object):
    def setupUi(self, nodegenDialog):
        nodegenDialog.setObjectName("nodegenDialog")
        nodegenDialog.resize(1013, 742)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        nodegenDialog.setFont(font)
        self.gridLayout = QtWidgets.QGridLayout(nodegenDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(nodegenDialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.splitter = QtWidgets.QSplitter(nodegenDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.kno_widget = QtWidgets.QTableWidget(self.splitter)
        self.kno_widget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.kno_widget.setAlternatingRowColors(True)
        self.kno_widget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.kno_widget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.kno_widget.setObjectName("kno_widget")
        self.kno_widget.setColumnCount(4)
        self.kno_widget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.kno_widget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.kno_widget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.kno_widget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.kno_widget.setHorizontalHeaderItem(3, item)
        self.kno_widget.verticalHeader().setVisible(False)
        self.groupBox_3 = QtWidgets.QGroupBox(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setMaximumSize(QtCore.QSize(600, 16777215))
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 1, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 0, 0, 1, 1)
        self.start_station = QtWidgets.QLineEdit(self.groupBox_3)
        self.start_station.setObjectName("start_station")
        self.gridLayout_4.addWidget(self.start_station, 0, 1, 1, 1)
        self.count = QtWidgets.QSpinBox(self.groupBox_3)
        self.count.setObjectName("count")
        self.gridLayout_4.addWidget(self.count, 2, 1, 1, 1)
        self.end_station = QtWidgets.QLineEdit(self.groupBox_3)
        self.end_station.setObjectName("end_station")
        self.gridLayout_4.addWidget(self.end_station, 1, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 2, 0, 1, 1)
        self.edit_name = QtWidgets.QTableWidget(self.groupBox_3)
        self.edit_name.setObjectName("edit_name")
        self.edit_name.setColumnCount(4)
        self.edit_name.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.edit_name.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.edit_name.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.edit_name.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.edit_name.setHorizontalHeaderItem(3, item)
        self.gridLayout_4.addWidget(self.edit_name, 4, 0, 1, 6)
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 3, 0, 1, 1)
        self.gef = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.gef.setDecimals(6)
        self.gef.setMinimum(-99.0)
        self.gef.setObjectName("gef")
        self.gridLayout_4.addWidget(self.gef, 3, 1, 1, 1)
        self.copy_rau = QtWidgets.QCheckBox(self.groupBox_3)
        self.copy_rau.setEnabled(False)
        self.copy_rau.setObjectName("copy_rau")
        self.gridLayout_4.addWidget(self.copy_rau, 1, 3, 1, 1)
        self.deletenodes = QtWidgets.QCheckBox(self.groupBox_3)
        self.deletenodes.setEnabled(False)
        self.deletenodes.setChecked(True)
        self.deletenodes.setObjectName("deletenodes")
        self.gridLayout_4.addWidget(self.deletenodes, 0, 3, 1, 1)
        self.copy_schalt = QtWidgets.QCheckBox(self.groupBox_3)
        self.copy_schalt.setEnabled(False)
        self.copy_schalt.setObjectName("copy_schalt")
        self.gridLayout_4.addWidget(self.copy_schalt, 2, 3, 1, 1)
        self.idno = QtWidgets.QLabel(self.groupBox_3)
        self.idno.setObjectName("idno")
        self.gridLayout_4.addWidget(self.idno, 3, 3, 1, 1)
        self.gridLayout.addWidget(self.splitter, 1, 0, 1, 3)
        self.groupBox = QtWidgets.QGroupBox(nodegenDialog)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 0, 0, 1, 1)
        self.dataname = QtWidgets.QLineEdit(self.groupBox)
        self.dataname.setObjectName("dataname")
        self.gridLayout_2.addWidget(self.dataname, 0, 1, 1, 1)
        self.overwrite = QtWidgets.QCheckBox(self.groupBox)
        self.overwrite.setObjectName("overwrite")
        self.gridLayout_2.addWidget(self.overwrite, 0, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 3, 1, 1)
        self.ok = QtWidgets.QPushButton(self.groupBox)
        self.ok.setMinimumSize(QtCore.QSize(100, 0))
        self.ok.setMaximumSize(QtCore.QSize(100, 16777215))
        self.ok.setAutoDefault(False)
        self.ok.setObjectName("ok")
        self.gridLayout_2.addWidget(self.ok, 0, 4, 1, 1)
        self.cancel = QtWidgets.QPushButton(self.groupBox)
        self.cancel.setMinimumSize(QtCore.QSize(100, 0))
        self.cancel.setMaximumSize(QtCore.QSize(100, 16777215))
        self.cancel.setAutoDefault(False)
        self.cancel.setObjectName("cancel")
        self.gridLayout_2.addWidget(self.cancel, 0, 5, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 2, 0, 1, 3)

        self.retranslateUi(nodegenDialog)
        QtCore.QMetaObject.connectSlotsByName(nodegenDialog)

    def retranslateUi(self, nodegenDialog):
        _translate = QtCore.QCoreApplication.translate
        nodegenDialog.setWindowTitle(_translate("nodegenDialog", "Erzeugung von Zusatzquerprofilen"))
        self.label.setText(_translate("nodegenDialog", "Muster Querschnitt Auswählen"))
        item = self.kno_widget.horizontalHeaderItem(0)
        item.setText(_translate("nodegenDialog", "ID"))
        item = self.kno_widget.horizontalHeaderItem(1)
        item.setText(_translate("nodegenDialog", "Station"))
        item = self.kno_widget.horizontalHeaderItem(2)
        item.setText(_translate("nodegenDialog", "Knoten"))
        item = self.kno_widget.horizontalHeaderItem(3)
        item.setText(_translate("nodegenDialog", "Name"))
        self.label_8.setText(_translate("nodegenDialog", "End Station"))
        self.label_7.setText(_translate("nodegenDialog", "Start Station"))
        self.label_9.setText(_translate("nodegenDialog", "Schnitt Count"))
        item = self.edit_name.horizontalHeaderItem(0)
        item.setText(_translate("nodegenDialog", "Schnitt"))
        item = self.edit_name.horizontalHeaderItem(1)
        item.setText(_translate("nodegenDialog", "Knoten"))
        item = self.edit_name.horizontalHeaderItem(2)
        item.setText(_translate("nodegenDialog", "Station"))
        item = self.edit_name.horizontalHeaderItem(3)
        item.setText(_translate("nodegenDialog", "Abstand"))
        self.label_4.setText(_translate("nodegenDialog", "Gefälle"))
        self.copy_rau.setText(_translate("nodegenDialog", "Rauheitsprofil Kopieren"))
        self.deletenodes.setText(_translate("nodegenDialog", "Zwischen liegenden Knoten Löschen"))
        self.copy_schalt.setText(_translate("nodegenDialog", "Schaltprofil Kopieren"))
        self.idno.setText(_translate("nodegenDialog", "ID:"))
        self.label_12.setText(_translate("nodegenDialog", "Neu Filename:"))
        self.overwrite.setText(_translate("nodegenDialog", "Overwrite Files"))
        self.ok.setText(_translate("nodegenDialog", "Update"))
        self.cancel.setText(_translate("nodegenDialog", "Cancel"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    nodegenDialog = QtWidgets.QDialog()
    ui = Ui_nodegenDialog()
    ui.setupUi(nodegenDialog)
    nodegenDialog.show()
    sys.exit(app.exec_())
