# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rauDialog.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_rauDialog(object):
    def setupUi(self, rauDialog):
        rauDialog.setObjectName("rauDialog")
        rauDialog.resize(1050, 672)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        rauDialog.setFont(font)
        self.gridLayout = QtWidgets.QGridLayout(rauDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.cancel = QtWidgets.QPushButton(rauDialog)
        self.cancel.setAutoDefault(False)
        self.cancel.setObjectName("cancel")
        self.gridLayout.addWidget(self.cancel, 3, 5, 1, 1)
        self._schaltercheck = QtWidgets.QCheckBox(rauDialog)
        self._schaltercheck.setObjectName("_schaltercheck")
        self.gridLayout.addWidget(self._schaltercheck, 3, 3, 1, 1)
        self.overwrite = QtWidgets.QCheckBox(rauDialog)
        self.overwrite.setObjectName("overwrite")
        self.gridLayout.addWidget(self.overwrite, 3, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(rauDialog)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(rauDialog)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 10))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 2)
        self.dataname = QtWidgets.QLineEdit(rauDialog)
        self.dataname.setObjectName("dataname")
        self.gridLayout.addWidget(self.dataname, 3, 1, 1, 1)
        self.ok = QtWidgets.QPushButton(rauDialog)
        self.ok.setAutoDefault(False)
        self.ok.setObjectName("ok")
        self.gridLayout.addWidget(self.ok, 3, 4, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(rauDialog)
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.splitter = QtWidgets.QSplitter(self.groupBox_3)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.nodes_table = QtWidgets.QTableWidget(self.splitter)
        self.nodes_table.setMinimumSize(QtCore.QSize(400, 0))
        self.nodes_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.nodes_table.setProperty("showDropIndicator", False)
        self.nodes_table.setDragDropOverwriteMode(False)
        self.nodes_table.setAlternatingRowColors(True)
        self.nodes_table.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.nodes_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.nodes_table.setColumnCount(4)
        self.nodes_table.setObjectName("nodes_table")
        self.nodes_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.nodes_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.nodes_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.nodes_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.nodes_table.setHorizontalHeaderItem(3, item)
        self.nodes_table.horizontalHeader().setStretchLastSection(True)
        self.nodes_table.verticalHeader().setVisible(False)
        self.groupBox = QtWidgets.QGroupBox(self.splitter)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_16 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 3, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 1, 1, 1, 2)
        self.f_xv = QtWidgets.QComboBox(self.groupBox)
        self.f_xv.setObjectName("f_xv")
        self.gridLayout_2.addWidget(self.f_xv, 6, 3, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("QLabel {\n"
"     outline-color: rgb(0, 150, 0);\n"
"}")
        self.label_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.gridLayout_2.addWidget(self.label_19, 3, 6, 1, 1)
        self.vs_kst2 = QtWidgets.QLineEdit(self.groupBox)
        self.vs_kst2.setEnabled(False)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.vs_kst2.setFont(font)
        self.vs_kst2.setStyleSheet("QLineEdit\n"
"{ \n"
"background-color: rgb(255,0,0);\n"
"color: rgb(255,255,255);\n"
"}")
        self.vs_kst2.setObjectName("vs_kst2")
        self.gridLayout_2.addWidget(self.vs_kst2, 5, 5, 1, 1)
        self.f_kst = QtWidgets.QDoubleSpinBox(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.f_kst.setFont(font)
        self.f_kst.setStyleSheet("QDoubleSpinBox\n"
"{ \n"
"background-color: rgb(0,0,255);\n"
"color: rgb(255,255,255);\n"
"}")
        self.f_kst.setProperty("value", 35.0)
        self.f_kst.setObjectName("f_kst")
        self.gridLayout_2.addWidget(self.f_kst, 5, 3, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 1, 5, 1, 2)
        self.vs_xb = QtWidgets.QComboBox(self.groupBox)
        self.vs_xb.setObjectName("vs_xb")
        self.gridLayout_2.addWidget(self.vs_xb, 6, 5, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.groupBox)
        self.label_18.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_18.setFont(font)
        self.label_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout_2.addWidget(self.label_18, 3, 5, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 6, 0, 1, 1)
        self.f_xb = QtWidgets.QComboBox(self.groupBox)
        self.f_xb.setObjectName("f_xb")
        self.gridLayout_2.addWidget(self.f_xb, 6, 4, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 5, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("QLabel {\n"
"     color: rgb(0, 0, 255);\n"
"}")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 4, 3, 1, 2)
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("QLabel {\n"
"     color: rgb(0, 150, 0);\n"
"}")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 4, 6, 1, 1)
        self.f_kst2 = QtWidgets.QLineEdit(self.groupBox)
        self.f_kst2.setEnabled(False)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.f_kst2.setFont(font)
        self.f_kst2.setStyleSheet("QLineEdit\n"
"{ \n"
"background-color: rgb(0,0,255);\n"
"color: rgb(255,255,255);\n"
"}")
        self.f_kst2.setObjectName("f_kst2")
        self.gridLayout_2.addWidget(self.f_kst2, 5, 4, 1, 1)
        self.vg_kst2 = QtWidgets.QLineEdit(self.groupBox)
        self.vg_kst2.setEnabled(False)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.vg_kst2.setFont(font)
        self.vg_kst2.setStyleSheet("QLineEdit\n"
"{ \n"
"background-color: rgb(0,150,0);\n"
"color: rgb(255,255,255);\n"
"}")
        self.vg_kst2.setObjectName("vg_kst2")
        self.gridLayout_2.addWidget(self.vg_kst2, 5, 6, 1, 1)
        self.vs_kst = QtWidgets.QDoubleSpinBox(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.vs_kst.setFont(font)
        self.vs_kst.setStyleSheet("QDoubleSpinBox\n"
"{ \n"
"background-color: rgb(255,0,0);\n"
"color: rgb(255,255,255);\n"
"}")
        self.vs_kst.setProperty("value", 15.0)
        self.vs_kst.setObjectName("vs_kst")
        self.gridLayout_2.addWidget(self.vs_kst, 5, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 3, 1, 2)
        self.rauView = PlotWidget(self.groupBox)
        self.rauView.setObjectName("rauView")
        self.gridLayout_2.addWidget(self.rauView, 7, 0, 1, 7)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("QLabel\n"
"{ \n"
"    color: rgb(255, 0, 0);\n"
"}")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 4, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("QLabel {\n"
"     color: rgb(0, 150, 0);\n"
"}")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 4, 1, 1, 1)
        self.vs_xv = QtWidgets.QComboBox(self.groupBox)
        self.vs_xv.setObjectName("vs_xv")
        self.gridLayout_2.addWidget(self.vs_xv, 6, 2, 1, 1)
        self.vg_xv = QtWidgets.QLineEdit(self.groupBox)
        self.vg_xv.setEnabled(False)
        self.vg_xv.setObjectName("vg_xv")
        self.gridLayout_2.addWidget(self.vg_xv, 6, 1, 1, 1)
        self.vg_xb = QtWidgets.QLineEdit(self.groupBox)
        self.vg_xb.setEnabled(False)
        self.vg_xb.setObjectName("vg_xb")
        self.gridLayout_2.addWidget(self.vg_xb, 6, 6, 1, 1)
        self.vg_kst = QtWidgets.QDoubleSpinBox(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.vg_kst.setFont(font)
        self.vg_kst.setStyleSheet("QDoubleSpinBox\n"
"{ \n"
"background-color: rgb(0,150,0);\n"
"color: rgb(255,255,255);\n"
"}")
        self.vg_kst.setProperty("value", 33.0)
        self.vg_kst.setObjectName("vg_kst")
        self.gridLayout_2.addWidget(self.vg_kst, 5, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.groupBox)
        self.label_17.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 3, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("QLabel\n"
"{ \n"
"    color: rgb(255, 0, 0);\n"
"}")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 4, 5, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 1)
        self.gridLayout_2.setColumnStretch(1, 1)
        self.gridLayout_2.setColumnStretch(2, 1)
        self.gridLayout_2.setColumnStretch(3, 1)
        self.gridLayout_2.setColumnStretch(4, 1)
        self.gridLayout_2.setColumnStretch(5, 1)
        self.gridLayout_2.setColumnStretch(6, 1)
        self.gridLayout_4.addWidget(self.splitter, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_3, 1, 0, 2, 6)

        self.retranslateUi(rauDialog)
        QtCore.QMetaObject.connectSlotsByName(rauDialog)

    def retranslateUi(self, rauDialog):
        _translate = QtCore.QCoreApplication.translate
        rauDialog.setWindowTitle(_translate("rauDialog", "Rauheitsprofil Erstellen"))
        self.cancel.setText(_translate("rauDialog", "Cancel"))
        self._schaltercheck.setText(_translate("rauDialog", "SCHALTPROFIL"))
        self.overwrite.setText(_translate("rauDialog", "Overwrite Files"))
        self.label_6.setText(_translate("rauDialog", "New Filename:"))
        self.label_5.setText(_translate("rauDialog", "Knoten Auswählen:"))
        self.ok.setText(_translate("rauDialog", "Erstellen"))
        self.nodes_table.setSortingEnabled(True)
        item = self.nodes_table.horizontalHeaderItem(0)
        item.setText(_translate("rauDialog", "Nodes"))
        item = self.nodes_table.horizontalHeaderItem(1)
        item.setText(_translate("rauDialog", "Station"))
        item = self.nodes_table.horizontalHeaderItem(2)
        item.setText(_translate("rauDialog", "ID"))
        item = self.nodes_table.horizontalHeaderItem(3)
        item.setText(_translate("rauDialog", "Schnitt"))
        self.label_16.setText(_translate("rauDialog", "mit Gras"))
        self.label_14.setText(_translate("rauDialog", "Vorland"))
        self.label_19.setText(_translate("rauDialog", "mit Gras"))
        self.vs_kst2.setText(_translate("rauDialog", "15"))
        self.label_15.setText(_translate("rauDialog", "Vorland"))
        self.label_18.setText(_translate("rauDialog", "<html><head/><body><p>mit Bäumern</p><p>und Sträuchern</p><p><br/></p></body></html>"))
        self.label_11.setText(_translate("rauDialog", "X:"))
        self.label.setText(_translate("rauDialog", "Strickler Wert:"))
        self.label_8.setText(_translate("rauDialog", "FB"))
        self.label_10.setText(_translate("rauDialog", "VG"))
        self.f_kst2.setText(_translate("rauDialog", "35"))
        self.vg_kst2.setText(_translate("rauDialog", "33"))
        self.label_2.setText(_translate("rauDialog", "Flussbett"))
        self.label_4.setText(_translate("rauDialog", "VS"))
        self.label_3.setText(_translate("rauDialog", "VG"))
        self.label_17.setText(_translate("rauDialog", "<html><head/><body><p>mit Bäumern</p><p>und Sträuchern</p><p><br/></p></body></html>"))
        self.label_9.setText(_translate("rauDialog", "VS"))


from pyqtgraph import PlotWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    rauDialog = QtWidgets.QDialog()
    ui = Ui_rauDialog()
    ui.setupUi(rauDialog)
    rauDialog.show()
    sys.exit(app.exec_())
