# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rauDialog.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_rauDialog(object):
    def setupUi(self, rauDialog):
        rauDialog.setObjectName("rauDialog")
        rauDialog.resize(737, 695)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        rauDialog.setFont(font)
        self.gridLayout = QtWidgets.QGridLayout(rauDialog)
        self.gridLayout.setObjectName("gridLayout")
        self._swert = QtWidgets.QLineEdit(rauDialog)
        self._swert.setEnabled(False)
        self._swert.setMinimumSize(QtCore.QSize(0, 0))
        self._swert.setMaximumSize(QtCore.QSize(120, 16777215))
        self._swert.setObjectName("_swert")
        self.gridLayout.addWidget(self._swert, 4, 5, 1, 1)
        self.label_4 = QtWidgets.QLabel(rauDialog)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 4, 1, 1)
        self._schaltercheck = QtWidgets.QCheckBox(rauDialog)
        self._schaltercheck.setObjectName("_schaltercheck")
        self.gridLayout.addWidget(self._schaltercheck, 3, 5, 1, 1)
        self._smodus = QtWidgets.QLineEdit(rauDialog)
        self._smodus.setEnabled(False)
        self._smodus.setMaximumSize(QtCore.QSize(120, 16777215))
        self._smodus.setObjectName("_smodus")
        self.gridLayout.addWidget(self._smodus, 5, 5, 1, 1)
        self.count = QtWidgets.QLCDNumber(rauDialog)
        self.count.setMinimumSize(QtCore.QSize(0, 70))
        self.count.setMaximumSize(QtCore.QSize(16777215, 80))
        self.count.setObjectName("count")
        self.gridLayout.addWidget(self.count, 1, 4, 2, 2)
        self.label_3 = QtWidgets.QLabel(rauDialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 5, 4, 1, 1)
        self.nodes_table = QtWidgets.QTableWidget(rauDialog)
        self.nodes_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.nodes_table.setProperty("showDropIndicator", False)
        self.nodes_table.setDragDropOverwriteMode(False)
        self.nodes_table.setAlternatingRowColors(True)
        self.nodes_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.nodes_table.setColumnCount(4)
        self.nodes_table.setObjectName("nodes_table")
        self.nodes_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.nodes_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.nodes_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.nodes_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.nodes_table.setHorizontalHeaderItem(3, item)
        self.nodes_table.horizontalHeader().setStretchLastSection(True)
        self.nodes_table.verticalHeader().setVisible(False)
        self.gridLayout.addWidget(self.nodes_table, 1, 0, 14, 3)
        self._modus = QtWidgets.QLineEdit(rauDialog)
        self._modus.setEnabled(False)
        self._modus.setMaximumSize(QtCore.QSize(120, 16777215))
        self._modus.setObjectName("_modus")
        self.gridLayout.addWidget(self._modus, 6, 5, 1, 1)
        self.label = QtWidgets.QLabel(rauDialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 6, 4, 1, 1)
        self.label_5 = QtWidgets.QLabel(rauDialog)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 10))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 2)
        self.dataname = QtWidgets.QLineEdit(rauDialog)
        self.dataname.setObjectName("dataname")
        self.gridLayout.addWidget(self.dataname, 15, 1, 1, 1)
        self.ok = QtWidgets.QPushButton(rauDialog)
        self.ok.setAutoDefault(False)
        self.ok.setObjectName("ok")
        self.gridLayout.addWidget(self.ok, 15, 4, 1, 1)
        self.cancel = QtWidgets.QPushButton(rauDialog)
        self.cancel.setAutoDefault(False)
        self.cancel.setObjectName("cancel")
        self.gridLayout.addWidget(self.cancel, 15, 5, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(rauDialog)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self._lmodus = QtWidgets.QLineEdit(self.groupBox)
        self._lmodus.setEnabled(False)
        self._lmodus.setMaximumSize(QtCore.QSize(120, 16777215))
        self._lmodus.setObjectName("_lmodus")
        self.gridLayout_2.addWidget(self._lmodus, 0, 2, 1, 1)
        self.samplerauX = QtWidgets.QTableWidget(self.groupBox)
        self.samplerauX.setMaximumSize(QtCore.QSize(120, 16777215))
        self.samplerauX.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.samplerauX.setAlternatingRowColors(True)
        self.samplerauX.setObjectName("samplerauX")
        self.samplerauX.setColumnCount(1)
        self.samplerauX.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.samplerauX.setHorizontalHeaderItem(0, item)
        self.samplerauX.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_2.addWidget(self.samplerauX, 2, 1, 2, 1)
        self.strickler = QtWidgets.QLineEdit(self.groupBox)
        self.strickler.setMaximumSize(QtCore.QSize(120, 16777215))
        self.strickler.setObjectName("strickler")
        self.gridLayout_2.addWidget(self.strickler, 1, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setMaximumSize(QtCore.QSize(180, 16777215))
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 1, 1, 1)
        self.samplerauY = QtWidgets.QTableWidget(self.groupBox)
        self.samplerauY.setMaximumSize(QtCore.QSize(120, 16777215))
        self.samplerauY.setAlternatingRowColors(True)
        self.samplerauY.setObjectName("samplerauY")
        self.samplerauY.setColumnCount(1)
        self.samplerauY.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.samplerauY.setHorizontalHeaderItem(0, item)
        self.samplerauY.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_2.addWidget(self.samplerauY, 2, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 7, 4, 8, 2)
        self.label_6 = QtWidgets.QLabel(rauDialog)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 15, 0, 1, 1)
        self.overwrite = QtWidgets.QCheckBox(rauDialog)
        self.overwrite.setObjectName("overwrite")
        self.gridLayout.addWidget(self.overwrite, 15, 2, 1, 1)

        self.retranslateUi(rauDialog)
        QtCore.QMetaObject.connectSlotsByName(rauDialog)

    def retranslateUi(self, rauDialog):
        _translate = QtCore.QCoreApplication.translate
        rauDialog.setWindowTitle(_translate("rauDialog", "Create Lamellen Profiles"))
        self._swert.setText(_translate("rauDialog", "120"))
        self.label_4.setText(_translate("rauDialog", "Anfangs Wert"))
        self._schaltercheck.setText(_translate("rauDialog", "Schalt Profil"))
        self._smodus.setText(_translate("rauDialog", "ZS"))
        self.label_3.setText(_translate("rauDialog", "Schaltprofil Modus"))
        self.nodes_table.setSortingEnabled(True)
        item = self.nodes_table.horizontalHeaderItem(0)
        item.setText(_translate("rauDialog", "Nodes"))
        item = self.nodes_table.horizontalHeaderItem(1)
        item.setText(_translate("rauDialog", "Station"))
        item = self.nodes_table.horizontalHeaderItem(2)
        item.setText(_translate("rauDialog", "ID"))
        item = self.nodes_table.horizontalHeaderItem(3)
        item.setText(_translate("rauDialog", "Schnitt"))
        self._modus.setText(_translate("rauDialog", "RS"))
        self.label.setText(_translate("rauDialog", "QuerschnittsProfil Modus"))
        self.label_5.setText(_translate("rauDialog", "Choose Nodes:"))
        self.ok.setText(_translate("rauDialog", "Create"))
        self.cancel.setText(_translate("rauDialog", "Cancel"))
        self.groupBox.setTitle(_translate("rauDialog", "Rauheitsprofil"))
        self._lmodus.setText(_translate("rauDialog", "H2"))
        item = self.samplerauX.horizontalHeaderItem(0)
        item.setText(_translate("rauDialog", "X"))
        self.strickler.setText(_translate("rauDialog", "35"))
        self.label_2.setText(_translate("rauDialog", "Anfangs Strickler Wert"))
        item = self.samplerauY.horizontalHeaderItem(0)
        item.setText(_translate("rauDialog", "Strickler"))
        self.label_11.setText(_translate("rauDialog", "Rauheitsprofil Modus"))
        self.label_6.setText(_translate("rauDialog", "New Filename:"))
        self.overwrite.setText(_translate("rauDialog", "Overwrite Files"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    rauDialog = QtWidgets.QDialog()
    ui = Ui_rauDialog()
    ui.setupUi(rauDialog)
    rauDialog.show()
    sys.exit(app.exec_())
